$axure.loadCurrentPage({
  "url":"hot_sale没有内容时.html",
  "generationDate":new Date(1451376400653.58),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"c94befe4c4ba4301868b47511e05df69",
    "type":"Axure:Page",
    "name":"hot sale没有内容时",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"8ec48697aa07459ba2c2aaa6906a3fe3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":10},
            "size":{
              "width":200,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9949aa952057426f9d67174a08bbeb10",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":10},
                "size":{
                  "width":200,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/专属栏目/u6.png"}},
{
          "id":"a0b0b41dc3124e7683a33e33f041c795",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":16},
            "size":{
              "width":20,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/专属栏目/u8_line.png"}},
{
          "id":"6915c8e62f244f33bdb2bc07c87bf581",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":22},
            "size":{
              "width":20,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/专属栏目/u8_line.png"}},
{
          "id":"041ce6594b25405581104c880fa025e3",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":29},
            "size":{
              "width":20,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/专属栏目/u8_line.png"}},
{
          "id":"6c9250ab9ccc4cea8d6a14748e4a3036",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF00},
            "location":{
              "x":26,
              "y":16},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e88b0c28626c44f99bf923a10261dfa7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF00},
                "location":{
                  "x":26,
                  "y":16},
                "size":{
                  "width":10,
                  "height":10}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/专属栏目/u11.png"}},
{
          "id":"47a73074cc024c12ae646079aa84bd8b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":328,
              "y":11},
            "size":{
              "width":40,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d6e0e3d597f410ebdfed2740520631f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":328,
                  "y":11},
                "size":{
                  "width":40,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/专属栏目/u13.png"}},
{
          "id":"d8a9928d46e4476487b21b960dd509ee",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":290,
              "y":16},
            "size":{
              "width":28,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7e7e72e36d384025b5d963121b98ec73",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":290,
                  "y":16},
                "size":{
                  "width":28,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/专属栏目/u15.png"}},
{
          "id":"7368736d6c2741288723dd9639bd43fa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":84,
              "y":18},
            "size":{
              "width":162,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"601d7b79df2d4e4bb3d82416412e1ae2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":84,
                  "y":18},
                "size":{
                  "width":162,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dac746f953994ebcb88c2ae016e2ae0a",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":49},
            "size":{
              "width":376,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/专属栏目/u21_line.png"}},
{
          "id":"5b009e379d3143f4823baa7164594741",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":82},
            "size":{
              "width":376,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/专属栏目/u21_line.png"}},
{
          "id":"d2535bdb0926491a877844a2b83cbd45",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":61},
            "size":{
              "width":366,
              "height":24}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onDrag":{
              "description":"OnDrag",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"moveWidget",
                      "description":"Move 类目 with drag x",
                      "objectsToMoves":[{
                          "objectPath":["0455045cc9644bdf84f57ea84198ec8c"],
                          "moveInfo":{
                            "moveType":"dragX",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "options":{
}}}]}]}]}},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"7f75fe6f93664fc78f925314db77cebd",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"0455045cc9644bdf84f57ea84198ec8c",
                  "label":"类目",
                  "parentDynamicPanel":"d2535bdb0926491a877844a2b83cbd45",
                  "type":"dynamicPanel",
                  "styleType":"dynamicPanel",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":-5},
                    "size":{
                      "width":10,
                      "height":10}},
                  "adaptiveStyles":{
},
                  "scrollbars":"none",
                  "fitToContent":true,
                  "propagate":false,
                  "diagrams":[{
                      "id":"a06f12de96034cb8bd9bd5c89af257cb",
                      "label":"State1",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"ead889d4f60c4d069f31a8d3178dc872",
                          "label":"",
                          "parentDynamicPanel":"0455045cc9644bdf84f57ea84198ec8c",
                          "type":"buttonShape",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontName":"'Arial Negreta', 'Arial'",
                            "fontWeight":"700",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFF9900,
                              "opacity":1},
                            "location":{
                              "x":0,
                              "y":5},
                            "size":{
                              "width":55,
                              "height":16}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"2f67b861aa8d4b7f87452f75e390c427",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"0455045cc9644bdf84f57ea84198ec8c",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fontName":"'Arial Negreta', 'Arial'",
                                "fontWeight":"700",
                                "foreGroundFill":{
                                  "fillType":"solid",
                                  "color":0xFFFF9900,
                                  "opacity":1},
                                "location":{
                                  "x":0,
                                  "y":5},
                                "size":{
                                  "width":55,
                                  "height":16}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}},
{
                          "id":"154e4c0c381e4a5db6e15d8472294fbe",
                          "label":"",
                          "parentDynamicPanel":"0455045cc9644bdf84f57ea84198ec8c",
                          "type":"buttonShape",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":74,
                              "y":5},
                            "size":{
                              "width":52,
                              "height":16}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"ffeb9524aeda48eebddd057e56ed8af1",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"0455045cc9644bdf84f57ea84198ec8c",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":74,
                                  "y":5},
                                "size":{
                                  "width":52,
                                  "height":16}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}},
{
                          "id":"e4907840d3e04e2b8e95e138538620cc",
                          "label":"",
                          "parentDynamicPanel":"0455045cc9644bdf84f57ea84198ec8c",
                          "type":"buttonShape",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":141,
                              "y":5},
                            "size":{
                              "width":94,
                              "height":16}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"a5bbc3718e2b48829db6bb8e7fd3ba4d",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"0455045cc9644bdf84f57ea84198ec8c",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":141,
                                  "y":5},
                                "size":{
                                  "width":94,
                                  "height":16}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}},
{
                          "id":"9596a6d02c66477cb0e82418fdc57f56",
                          "label":"",
                          "parentDynamicPanel":"0455045cc9644bdf84f57ea84198ec8c",
                          "type":"buttonShape",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":250,
                              "y":5},
                            "size":{
                              "width":109,
                              "height":16}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"51cb0a04421a4e189778afc686b7157c",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"0455045cc9644bdf84f57ea84198ec8c",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":250,
                                  "y":5},
                                "size":{
                                  "width":109,
                                  "height":16}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}},
{
                          "id":"6cc82692b20e4096ba509ab088a601d0",
                          "label":"",
                          "parentDynamicPanel":"0455045cc9644bdf84f57ea84198ec8c",
                          "type":"imageBox",
                          "styleType":"imageBox",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":369,
                              "y":5},
                            "size":{
                              "width":157,
                              "height":24},
                            "rotation":"0",
                            "textRotation":"0",
                            "borderWidth":"0",
                            "cornerRadiusTopLeft":"0"},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"f4e2d5553cb3443890d869307a67a4b6",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"0455045cc9644bdf84f57ea84198ec8c",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":369,
                                  "y":5},
                                "size":{
                                  "width":157,
                                  "height":24},
                                "rotation":"0",
                                "textRotation":"0",
                                "borderWidth":"0",
                                "cornerRadiusTopLeft":"0"},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/专属栏目/u32.png"}},
{
                          "id":"519bb5b8ee0a4e328608c898f330b618",
                          "label":"",
                          "parentDynamicPanel":"0455045cc9644bdf84f57ea84198ec8c",
                          "type":"imageBox",
                          "styleType":"imageBox",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":753,
                              "y":1},
                            "size":{
                              "width":157,
                              "height":27},
                            "rotation":"0",
                            "textRotation":"0",
                            "borderWidth":"0",
                            "cornerRadiusTopLeft":"0"},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"5ca874bba6744829bed5e6de0ebce671",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"0455045cc9644bdf84f57ea84198ec8c",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":753,
                                  "y":1},
                                "size":{
                                  "width":157,
                                  "height":27},
                                "rotation":"0",
                                "textRotation":"0",
                                "borderWidth":"0",
                                "cornerRadiusTopLeft":"0"},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/专属栏目/u34.png"}},
{
                          "id":"8420071953854d84bc9dbf51ca7b8d65",
                          "label":"",
                          "parentDynamicPanel":"0455045cc9644bdf84f57ea84198ec8c",
                          "type":"imageBox",
                          "styleType":"imageBox",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":482,
                              "y":0},
                            "size":{
                              "width":157,
                              "height":29},
                            "rotation":"0",
                            "textRotation":"0",
                            "borderWidth":"0",
                            "cornerRadiusTopLeft":"0"},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"9f3ea5005899494dbbdd2fb5958f23de",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"0455045cc9644bdf84f57ea84198ec8c",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":482,
                                  "y":0},
                                "size":{
                                  "width":157,
                                  "height":29},
                                "rotation":"0",
                                "textRotation":"0",
                                "borderWidth":"0",
                                "cornerRadiusTopLeft":"0"},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/专属栏目/u81.png"}},
{
                          "id":"0f58e1b09a484f73ae3a3246f21fe553",
                          "label":"",
                          "parentDynamicPanel":"0455045cc9644bdf84f57ea84198ec8c",
                          "type":"buttonShape",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontName":"'Arial Negreta', 'Arial'",
                            "fontWeight":"700",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFF9900,
                              "opacity":1},
                            "location":{
                              "x":644,
                              "y":6},
                            "size":{
                              "width":102,
                              "height":16}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"96e066f2869047f7bfe3dd11cbfcb473",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"0455045cc9644bdf84f57ea84198ec8c",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fontName":"'Arial Negreta', 'Arial'",
                                "fontWeight":"700",
                                "foreGroundFill":{
                                  "fillType":"solid",
                                  "color":0xFFFF9900,
                                  "opacity":1},
                                "location":{
                                  "x":644,
                                  "y":6},
                                "size":{
                                  "width":102,
                                  "height":16}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}}]}]}]}]},
{
          "id":"862cad0a55a2419482016de414fee769",
          "label":"all",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":350,
              "y":54},
            "size":{
              "width":26,
              "height":34}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"c4b56f117d1b43158e241bab4c740c38",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"9785cdc5b3784d178141dc503b9d753c",
                  "label":"",
                  "parentDynamicPanel":"862cad0a55a2419482016de414fee769",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":26,
                      "height":34},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9bbce2215eb141a1918104a9da502416",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"862cad0a55a2419482016de414fee769",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":26,
                          "height":34},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFD7D7D7}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"Set all to State2",
                              "panelsToStates":[{
                                  "panelPath":["862cad0a55a2419482016de414fee769"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]},
{
                              "action":"fadeWidget",
                              "description":"Show/Hide Widget",
                              "objectsToFades":[]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/专属栏目/u86.png"}}]},
{
              "id":"13d81a364643443bac57acdbe6573404",
              "label":"State2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"3728f0e002f24fe2b8db56bb9278325a",
                  "label":"",
                  "parentDynamicPanel":"862cad0a55a2419482016de414fee769",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":26,
                      "height":34},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9f56d22e1c2e4065a09ab31b87923d9f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"862cad0a55a2419482016de414fee769",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":26,
                          "height":34},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFD7D7D7}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"Show/Hide Widget",
                              "objectsToFades":[]},
{
                              "action":"setPanelState",
                              "description":"Set all to State1",
                              "panelsToStates":[{
                                  "panelPath":["862cad0a55a2419482016de414fee769"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/专属栏目/u86.png"}}]}]},
{
          "id":"a882ccd89af149a38e03d8e1b587d1cb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":93,
              "y":234},
            "size":{
              "width":214,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"647b63337e4b4dfba6dc29a364d98f26",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":93,
                  "y":234},
                "size":{
                  "width":214,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "8ec48697aa07459ba2c2aaa6906a3fe3":{
      "scriptId":"u0"},
    "9949aa952057426f9d67174a08bbeb10":{
      "scriptId":"u1"},
    "a0b0b41dc3124e7683a33e33f041c795":{
      "scriptId":"u2"},
    "6915c8e62f244f33bdb2bc07c87bf581":{
      "scriptId":"u3"},
    "041ce6594b25405581104c880fa025e3":{
      "scriptId":"u4"},
    "6c9250ab9ccc4cea8d6a14748e4a3036":{
      "scriptId":"u5"},
    "e88b0c28626c44f99bf923a10261dfa7":{
      "scriptId":"u6"},
    "47a73074cc024c12ae646079aa84bd8b":{
      "scriptId":"u7"},
    "8d6e0e3d597f410ebdfed2740520631f":{
      "scriptId":"u8"},
    "d8a9928d46e4476487b21b960dd509ee":{
      "scriptId":"u9"},
    "7e7e72e36d384025b5d963121b98ec73":{
      "scriptId":"u10"},
    "7368736d6c2741288723dd9639bd43fa":{
      "scriptId":"u11"},
    "601d7b79df2d4e4bb3d82416412e1ae2":{
      "scriptId":"u12"},
    "dac746f953994ebcb88c2ae016e2ae0a":{
      "scriptId":"u13"},
    "5b009e379d3143f4823baa7164594741":{
      "scriptId":"u14"},
    "d2535bdb0926491a877844a2b83cbd45":{
      "scriptId":"u15"},
    "0455045cc9644bdf84f57ea84198ec8c":{
      "scriptId":"u16"},
    "ead889d4f60c4d069f31a8d3178dc872":{
      "scriptId":"u17"},
    "2f67b861aa8d4b7f87452f75e390c427":{
      "scriptId":"u18"},
    "154e4c0c381e4a5db6e15d8472294fbe":{
      "scriptId":"u19"},
    "ffeb9524aeda48eebddd057e56ed8af1":{
      "scriptId":"u20"},
    "e4907840d3e04e2b8e95e138538620cc":{
      "scriptId":"u21"},
    "a5bbc3718e2b48829db6bb8e7fd3ba4d":{
      "scriptId":"u22"},
    "9596a6d02c66477cb0e82418fdc57f56":{
      "scriptId":"u23"},
    "51cb0a04421a4e189778afc686b7157c":{
      "scriptId":"u24"},
    "6cc82692b20e4096ba509ab088a601d0":{
      "scriptId":"u25"},
    "f4e2d5553cb3443890d869307a67a4b6":{
      "scriptId":"u26"},
    "519bb5b8ee0a4e328608c898f330b618":{
      "scriptId":"u27"},
    "5ca874bba6744829bed5e6de0ebce671":{
      "scriptId":"u28"},
    "8420071953854d84bc9dbf51ca7b8d65":{
      "scriptId":"u29"},
    "9f3ea5005899494dbbdd2fb5958f23de":{
      "scriptId":"u30"},
    "0f58e1b09a484f73ae3a3246f21fe553":{
      "scriptId":"u31"},
    "96e066f2869047f7bfe3dd11cbfcb473":{
      "scriptId":"u32"},
    "862cad0a55a2419482016de414fee769":{
      "scriptId":"u33"},
    "9785cdc5b3784d178141dc503b9d753c":{
      "scriptId":"u34"},
    "9bbce2215eb141a1918104a9da502416":{
      "scriptId":"u35"},
    "3728f0e002f24fe2b8db56bb9278325a":{
      "scriptId":"u36"},
    "9f56d22e1c2e4065a09ab31b87923d9f":{
      "scriptId":"u37"},
    "a882ccd89af149a38e03d8e1b587d1cb":{
      "scriptId":"u38"},
    "647b63337e4b4dfba6dc29a364d98f26":{
      "scriptId":"u39"}}});