//订单列表依赖的公用tools
$IMPORT('src/common/tools/fastclick.js');
$IMPORT('src/common/tools/jquery.cookie.js');
$IMPORT('src/common/ui/iscroll.js');
//订单列表依赖的公用业务功能模块
$IMPORT('src/common/config.js');
$IMPORT('src/common/langLoader.js');
$IMPORT('src/common/tc.js');
$IMPORT('src/common/checkoutflow/dataErrorLog.js');
$IMPORT('src/common/checkoutflow/popupTip.js');
$IMPORT('src/common/mydhgate/contactSeller.js');
$IMPORT('src/common/mydhgate/ifLogIn.js');
$IMPORT('src/common/mydhgate/order/cancelOrder.js');
$IMPORT('src/common/mydhgate/order/shippedOrder.js');
$IMPORT('src/common/mydhgate/order/toPayOrder.js');
//订单列表模版
$IMPORT('src/order/tpl/orderListTpl.js');
//订单列表功能模块
$IMPORT('src/order/orderList.js');
$IMPORT('src/order/orderType.js');
$IMPORT('src/order/index.js');
$IMPORT('src/order/main.js');
