//搜索列表依赖的公用tools
$IMPORT('src/common/tools/fastclick.js');
$IMPORT('src/common/tools/jquery.cookie.js');
$IMPORT('src/common/tools/deeplink.js');
//搜索列表依赖的公用业务功能模板
$IMPORT('src/common/tpl/appSpreadTpl.js');
$IMPORT('src/common/tpl/header/hotKeyWordTpl.js');
$IMPORT('src/common/tpl/header/recentKeyWordTpl.js');
$IMPORT('src/common/tpl/header/suggestTpl.js');
$IMPORT('src/common/tpl/header/topMenuInitTpl.js');
$IMPORT('src/common/tpl/header/topMenuOneCategoriesTpl.js');
$IMPORT('src/common/tpl/header/turnToLanguagesWebsiteTpl.js');
$IMPORT('src/common/tpl/recommend/youMyLikeTpl.js');
$IMPORT('src/common/tpl/recommend/youViewedTpl.js');
//搜索列表依赖的公用业务功能模块
$IMPORT('src/common/config.js');
$IMPORT('src/common/langLoader.js');
$IMPORT('src/common/serverTime.js');
$IMPORT('src/common/appopen.js');
$IMPORT('src/common/appSpread.js');
$IMPORT('src/common/header/buyerUserInfo.js');
$IMPORT('src/common/header/hotKeyWord.js');
$IMPORT('src/common/header/recentKeyWord.js');
$IMPORT('src/common/header/suggest.js');
$IMPORT('src/common/header/topSearch.js');
$IMPORT('src/common/header/topMenuInit.js');
$IMPORT('src/common/header/topMenuOneCategories.js');
$IMPORT('src/common/header/turnToLanguagesWebsite.js');
$IMPORT('src/common/sharesns.js');
$IMPORT('src/common/recommend/youMyLike.js');
$IMPORT('src/common/recommend/youViewed.js');
$IMPORT('src/common/checkoutflow/dataErrorLog.js');
$IMPORT('src/common/checkoutflow/popupTip.js');
$IMPORT('src/common/tc.js');
//搜索列表模板
$IMPORT('src/search/v1/tpl/filtersTpl.js');
$IMPORT('src/search/v1/tpl/sortByTpl.js');
//搜索列表功能模块
$IMPORT('src/search/v1/getGlobalVariables.js');
$IMPORT('src/search/v1/addToFav.js');
$IMPORT('src/search/v1/filters.js');
$IMPORT('src/search/v1/cateFilter.js');
$IMPORT('src/search/v1/lazyload.js');
$IMPORT('src/search/v1/sortBy.js');
$IMPORT('src/search/v1/gotoTop.js');
$IMPORT('src/search/v1/multiDimension/relateWord.js');
$IMPORT('src/search/v1/multiDimension/index.js');
$IMPORT('src/search/v1/multiDimension/main.js');