$axure.loadCurrentPage({
  "url":"首页.html",
  "generationDate":new Date(1451376400345.58),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"8e8178fd2a824a7db8c9ed34930ab543",
    "type":"Axure:Page",
    "name":"首页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"61942537d3504e0a81f0f627a76c6ade",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":307,
              "height":545}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d425b675fa83467cb46b6532c3ad7aa6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":307,
                  "height":545}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u0.png"}},
{
          "id":"f5139579b4224c2f93db9cae2bb99323",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":317,
              "y":414},
            "size":{
              "width":113,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"31fb3a1d74804e73b01e9d1df5c0ce83",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":317,
                  "y":414},
                "size":{
                  "width":113,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "61942537d3504e0a81f0f627a76c6ade":{
      "scriptId":"u0"},
    "d425b675fa83467cb46b6532c3ad7aa6":{
      "scriptId":"u1"},
    "f5139579b4224c2f93db9cae2bb99323":{
      "scriptId":"u2"},
    "31fb3a1d74804e73b01e9d1df5c0ce83":{
      "scriptId":"u3"}}});