//公用头尾依赖的公用tools
$IMPORT('src/common/tools/fastclick.js');
$IMPORT('src/common/tools/jquery.cookie.js');
$IMPORT('src/common/tools/deeplink.js');
//公用头尾依赖的公用业务功能模板
$IMPORT('src/common/tpl/appSpreadTpl.js');
$IMPORT('src/common/tpl/hotKeyWordTpl.js');
$IMPORT('src/common/tpl/recentKeyWordTpl.js');
$IMPORT('src/common/tpl/suggestTpl.js');
$IMPORT('src/common/tpl/topMenuInitTpl.js');
$IMPORT('src/common/tpl/topMenuOneCategoriesTpl.js');
$IMPORT('src/common/tpl/turnToLanguagesWebsiteTpl.js');
//公用头尾依赖的公用业务功能模块
$IMPORT('src/common/config.js');
$IMPORT('src/common/langLoader.js');
$IMPORT('src/common/serverTime.js');
$IMPORT('src/common/appopen.js');
$IMPORT('src/common/appSpread.js');
$IMPORT('src/common/buyerUserInfo.js');
$IMPORT('src/common/hotKeyWord.js');
$IMPORT('src/common/recentKeyWord.js');
$IMPORT('src/common/suggest.js');
$IMPORT('src/common/topSearch.js');
$IMPORT('src/common/topMenuInit.js');
$IMPORT('src/common/topMenuOneCategories.js');
$IMPORT('src/common/turnToLanguagesWebsite.js');
$IMPORT('src/common/sharesns.js');
$IMPORT('src/common/headfoot/index.js');
$IMPORT('src/common/headfoot/main.js');