//支付页依赖的公用tools
$IMPORT('src/common/tools/fastclick.js');
$IMPORT('src/common/tools/jquery.cookie.js');
//支付页依赖的公用业务功能模块
$IMPORT('src/common/config.js');
$IMPORT('src/common/langLoader.js');
$IMPORT('src/common/checkoutflow/getUserInfo.js');
$IMPORT('src/common/checkoutflow/dataErrorLog.js');
$IMPORT('src/common/checkoutflow/popupTip.js');
$IMPORT('src/common/checkoutflow/regexpConfig.js');
$IMPORT('src/common/checkoutflow/getCountrysData.js');
$IMPORT('src/common/checkoutflow/getStatesData.js');
$IMPORT('src/common/checkoutflow/thirdPartyCode.js');
//支付页模板
$IMPORT('src/payment/tpl/payTpl.js');
$IMPORT('src/payment/tpl/editBillingAddressTpl.js');
$IMPORT('src/payment/tpl/addCardAndPayTpl.js');
//支付页功能模块
$IMPORT('src/payment/ideal.js');
$IMPORT('src/payment/rbs.js');
$IMPORT('src/payment/sofort.js');
$IMPORT('src/payment/giropay.js');
$IMPORT('src/payment/addCardAndBillingAddress.js');
$IMPORT('src/payment/addCardAndPay.js');
$IMPORT('src/payment/cardPayJump.js');
$IMPORT('src/payment/editBillingAddress.js');
$IMPORT('src/payment/getCardAndDhpayInfo.js');
$IMPORT('src/payment/pay.js');
$IMPORT('src/payment/index.js');
$IMPORT('src/payment/main.js');