//支付成功页依赖的公用tools
$IMPORT('src/common/tools/fastclick.js');
$IMPORT('src/common/tools/jquery.cookie.js');
$IMPORT('src/common/tools/deeplink.js');
//支付成功页依赖的公用业务功能模块
$IMPORT('src/common/config.js');
$IMPORT('src/common/langLoader.js');
$IMPORT('src/common/appopen.js');
$IMPORT('src/common/checkoutflow/getUserInfo.js');
$IMPORT('src/common/checkoutflow/dataErrorLog.js');
$IMPORT('src/common/checkoutflow/popupTip.js');
$IMPORT('src/common/checkoutflow/regexpConfig.js');
$IMPORT('src/common/checkoutflow/thirdPartyCode.js');
//支付成功页模板
$IMPORT('src/paysucc/tpl/paysuccTpl.js');
//支付成功页功能模块
$IMPORT('src/paysucc/modifyPassword.js');
$IMPORT('src/paysucc/paySucc.js');
$IMPORT('src/paysucc/index.js');
$IMPORT('src/paysucc/main.js');