{
    "data": {
        "itemWinDtos": [
            {
                "isfreeShipping": true, 
                "ispromo": false, 
                "itemImgUrl": "http://www.dhresource.com/260x260/f2/albu/g3/M01/09/57/rBVaHFWwYc-ASaexAAFiWVXFgLE967.jpg", 
                "itemName": "Mix 6 desgin Snap Jewelry Necklace Snake Chain Round Silver Tone Clear Rhinestone Ginger necklace", 
                "itemWinPromoDto": { }, 
                "itemcode": "248353276", 
                "maxPrice": 2.5, 
                "measureName": "Piece", 
                "minOrder": 18, 
                "minPrice": 1.37, 
                "seoItemName": "mix-6-desgin-snap-jewelry-necklace-snake", 
                "soldNum": 160
            }, 
            {
                "isfreeShipping": true, 
                "ispromo": false, 
                "itemImgUrl": "http://www.dhresource.com/260x260/f2/albu/g3/M01/92/08/rBVaHFXajoGAZbuSAAH1Wo8JU3A081.jpg", 
                "itemName": "Mix Styles Crystal Jewelry charms Pendant Flower Heart necklace Snap Noosa DIY Jewelry Valentine,s day gift with snake chain N65", 
                "itemWinPromoDto": { }, 
                "itemcode": "252441573", 
                "maxPrice": 2.28, 
                "measureName": "Piece", 
                "minOrder": 20, 
                "minPrice": 1.37, 
                "seoItemName": "mix-styles-crystal-jewelry-charms-pendant", 
                "soldNum": 40
            }, 
            {
                "isfreeShipping": true, 
                "ispromo": false, 
                "itemImgUrl": "http://www.dhresource.com/260x260/f2/albu/g3/M00/6D/70/rBVaHVWwUfCAdwe_AAW4pEt8qyk761.jpg", 
                "itemName": "Crystal Diamond NOOSA Metal Snap Button Cuff Bracelet Interchangeable Jewelry Ginger Snaps Jewelry diy bracelet", 
                "itemWinPromoDto": { }, 
                "itemcode": "248346680", 
                "maxPrice": 2.5, 
                "measureName": "Piece", 
                "minOrder": 12, 
                "minPrice": 1.79, 
                "seoItemName": "crystal-diamond-noosa-metal-snap-button-cuff", 
                "soldNum": 148
            }, 
            {
                "isfreeShipping": true, 
                "ispromo": false, 
                "itemImgUrl": "http://www.dhresource.com/albu_481734797_00/1.260x260.jpg", 
                "itemName": "Antique Silver Charm Love Infinity Hunger Games Birds Braided Brown cord Leather Mixed Bracelet Wristbands Xmas Gift jewelry hy1039", 
                "itemWinPromoDto": { }, 
                "itemcode": "175261547", 
                "maxPrice": 1.65, 
                "measureName": "Piece", 
                "minOrder": 20, 
                "minPrice": 0.88, 
                "seoItemName": "antique-silver-charm-love-infinity-hunger", 
                "soldNum": 20
            }, 
            {
                "isfreeShipping": true, 
                "ispromo": false, 
                "itemImgUrl": "http://www.dhresource.com/albu_454272696_00/1.260x260.jpg", 
                "itemName": "20pcs lot arrow anchor Charm Bracelet Infinity Bracelet Braided Bracelet leather wrap bracelets fashion jewelry jewlery hy627", 
                "itemWinPromoDto": { }, 
                "itemcode": "179680281", 
                "maxPrice": 1.85, 
                "measureName": "Piece", 
                "minOrder": 20, 
                "minPrice": 1.28, 
                "seoItemName": "20pcs-lot-arrow-anchor-charm-bracelet-infinity", 
                "soldNum": 5
            }, 
            {
                "isfreeShipping": true, 
                "ispromo": false, 
                "itemImgUrl": "http://www.dhresource.com/260x260/f2/albu/g1/M01/60/25/rBVaGVW_OVCAH6S4AAFh9nLAF4s572.jpg", 
                "itemName": "9colors choose 100M 3mm x 1.5mm Flat Faux Suede Korean Velvet Leather Cord string Rope Thread Lace Findings", 
                "itemWinPromoDto": { }, 
                "itemcode": "249932580", 
                "maxPrice": 0.13, 
                "measureName": "Meter", 
                "minOrder": 100, 
                "minPrice": 0.09, 
                "seoItemName": "9colors-choose-100m-3mm-x-1-5mm-flat-faux", 
                "soldNum": 100
            }, 
            {
                "isfreeShipping": true, 
                "ispromo": false, 
                "itemImgUrl": "http://www.dhresource.com/260x260/f2/albu/g2/M01/F6/47/rBVaGlUHkciAbtUkAAL8hr9aIBQ128.jpg", 
                "itemName": "20 styles choose Cartoon Korean Lovers Summer Original Sweet Personality Couple T-shirt Short-Sleeve Valentine Wife Boyfriend Girls T01", 
                "itemWinPromoDto": { }, 
                "itemcode": "231728763", 
                "maxPrice": 11.37, 
                "measureName": "Set", 
                "minOrder": 1, 
                "minPrice": 7.33, 
                "seoItemName": "20-styles-choose-cartoon-korean-lovers-summer", 
                "soldNum": 22
            }, 
            {
                "isfreeShipping": true, 
                "ispromo": false, 
                "itemImgUrl": "http://www.dhresource.com/260x260/f2/albu/g1/M00/9E/A7/rBVaGFQuHyaAKPObAAPcrgztD5c778.jpg", 
                "itemName": "Frozen Lace Crown Hair Clip Accessories Princess Barrettes for christmas gift Mix colors BA135", 
                "itemWinPromoDto": { }, 
                "itemcode": "210848602", 
                "maxPrice": 1.64, 
                "measureName": "Piece", 
                "minOrder": 24, 
                "minPrice": 1.21, 
                "seoItemName": "frozen-lace-crown-hair-clip-accessories-princess", 
                "soldNum": 24
            }, 
            {
                "isfreeShipping": true, 
                "ispromo": false, 
                "itemImgUrl": "http://www.dhresource.com/albu_585784156_00/1.260x260.jpg", 
                "itemName": "Mix style 200pcs lot mix color AAA+ DIY Big hole beautiful European loose beads glass beads fiit for charm bracelets and necklace B06", 
                "itemWinPromoDto": { }, 
                "itemcode": "183699037", 
                "maxPrice": 0.17, 
                "measureName": "Piece", 
                "minOrder": 200, 
                "minPrice": 0.11, 
                "seoItemName": "mix-style-200pcs-lot-mix-color-aaa-diy-big", 
                "soldNum": 5
            }, 
            {
                "isfreeShipping": true, 
                "ispromo": false, 
                "itemImgUrl": "http://www.dhresource.com/albu_918841774_00/1.260x260.jpg", 
                "itemName": "Fashion Winter Dress slim hip long-sleeve casual dress solid leather & button decoration black red beige S-3XXL women plus size WS64", 
                "itemWinPromoDto": { }, 
                "itemcode": "209980372", 
                "maxPrice": 11.94, 
                "measureName": "Piece", 
                "minOrder": 1, 
                "minPrice": 8.38, 
                "seoItemName": "fashion-winter-dress-slim-hip-long-sleeve", 
                "soldNum": 21
            }, 
            {
                "isfreeShipping": true, 
                "ispromo": false, 
                "itemImgUrl": "http://www.dhresource.com/260x260/f2/albu/g2/M01/68/B9/rBVaG1UGVFmAT772AAGo8wKy6Cw294.jpg", 
                "itemName": "Mix style Vintage Noosa charms Pendant heart owls with crystal Snap Noosa for Necklace and bracelets DIY Jewelry Valentine,s day gift N56", 
                "itemWinPromoDto": { }, 
                "itemcode": "231598873", 
                "maxPrice": 2.4, 
                "measureName": "Piece", 
                "minOrder": 24, 
                "minPrice": 1.68, 
                "seoItemName": "mix-style-vintage-noosa-charms-pendant-heart", 
                "soldNum": 48
            }, 
            {
                "isfreeShipping": true, 
                "ispromo": false, 
                "itemImgUrl": "http://www.dhresource.com/260x260/f2/albu/g2/M01/34/77/rBVaG1XmWymAFxucAANRJXVrCCY014.jpg", 
                "itemName": "Infinity Bronze Butterfly snap leather bracelet styles choose friendship Noosa jewellry for gift customs diy making", 
                "itemWinPromoDto": { }, 
                "itemcode": "253730579", 
                "maxPrice": 1.94, 
                "measureName": "Piece", 
                "minOrder": 10, 
                "minPrice": 1.16, 
                "seoItemName": "infinity-bronze-butterfly-snap-leather-bracelet", 
                "soldNum": 10
            }, 
            {
                "isfreeShipping": true, 
                "ispromo": false, 
                "itemImgUrl": "http://www.dhresource.com/260x260/f2/albu/g2/M01/31/F7/rBVaGlXmWxyAX9pEAARU2TUSMoc532.jpg", 
                "itemName": "Infinity snap leather bracelet styles choose friendship snap jewellry for gift customs diy making", 
                "itemWinPromoDto": { }, 
                "itemcode": "253719985", 
                "maxPrice": 1.94, 
                "measureName": "Piece", 
                "minOrder": 10, 
                "minPrice": 1.16, 
                "seoItemName": "infinity-snap-leather-bracelet-styles-choose", 
                "soldNum": 80
            }, 
            {
                "isfreeShipping": true, 
                "ispromo": true, 
                "itemImgUrl": "http://www.dhresource.com/albu_421076023_00/1.260x260.jpg", 
                "itemName": "braided men and women Leather Rope Bracelets Multilayer ethnic Charm Bracelet Brown and black 20pcs lot", 
                "itemWinPromoDto": {
                    "discountRate": 40, 
                    "dynamicType": 1, 
                    "promoMaxPrice": 1.23, 
                    "promoMinPrice": 0.79, 
                    "promoTypeId": 0, 
                    "promoclass": "off-ico2"
                }, 
                "itemcode": "169230984", 
                "maxPrice": 2.05, 
                "measureName": "Piece", 
                "minOrder": 20, 
                "minPrice": 1.32, 
                "seoItemName": "braided-mens-and-women-leather-rope-bracelets", 
                "soldNum": 70
            }, 
            {
                "isfreeShipping": true, 
                "ispromo": false, 
                "itemImgUrl": "http://www.dhresource.com/260x260/f2/albu/g3/M01/E1/B7/rBVaHFRyleWAIZhwAAI1Ft2uEoo665.jpg", 
                "itemName": "Pink Frozen friendship infinity Bracelets Believe Love Sideways Charm Queen Elsa princess Anna infinity Wristband girls christmas gift", 
                "itemWinPromoDto": { }, 
                "itemcode": "213815309", 
                "maxPrice": 1.82, 
                "measureName": "Piece", 
                "minOrder": 20, 
                "minPrice": 1.37, 
                "seoItemName": "pink-frozen-friendship-infinity-bracelets", 
                "soldNum": 965
            }, 
            {
                "isfreeShipping": false, 
                "ispromo": false, 
                "itemImgUrl": "http://www.dhresource.com/260x260/f2/albu/g2/M01/66/03/rBVaGlYCBFqAIj3qAAE1S_WaKDw340.jpg", 
                "itemName": "5pcs lot handmade snap leather Bracelets Fit Snaps Snap Buttons 18mm with adjustable knot Free Shipping giger snap jewelry", 
                "itemWinPromoDto": { }, 
                "itemcode": "256716260", 
                "maxPrice": 2, 
                "measureName": "Piece", 
                "minOrder": 5, 
                "minPrice": 1.84, 
                "seoItemName": "5pcs-lot-handmade-snap-leather-bracelets", 
                "soldNum": 2
            }, 
            {
                "isfreeShipping": true, 
                "ispromo": false, 
                "itemImgUrl": "http://www.dhresource.com/albu_841222723_00/1.260x260.jpg", 
                "itemName": "24 colors high quality Waxed Cotton Cords For Wax Jewelry Making DIY Bead String Bracelet Sewing Leather Necklace 1mm 90 Meters", 
                "itemWinPromoDto": { }, 
                "itemcode": "202400271", 
                "maxPrice": 0.13, 
                "measureName": "Meter", 
                "minOrder": 90, 
                "minPrice": 0.11, 
                "seoItemName": "24-colors-high-quality-waxed-cotton-cords", 
                "soldNum": 830
            }, 
            {
                "isfreeShipping": true, 
                "ispromo": false, 
                "itemImgUrl": "http://www.dhresource.com/albu_454492717_00/1.260x260.jpg", 
                "itemName": "Women's Long Sleeve Lace sweater Round Neck Knit Sweater Tops Hem Mini Keep Warm Dresses sweater Fall&Winter 8 colors WS21", 
                "itemWinPromoDto": { }, 
                "itemcode": "173022226", 
                "maxPrice": 21.6, 
                "measureName": "Piece", 
                "minOrder": 1, 
                "minPrice": 16.92, 
                "seoItemName": "women-s-long-sleeve-round-neck-knit-sweater", 
                "soldNum": 1
            }, 
            {
                "isfreeShipping": true, 
                "ispromo": false, 
                "itemImgUrl": "http://www.dhresource.com/260x260/f2/albu/g3/M00/68/45/rBVaHVXexpGAVTk6AAGMWHMo9-I859.jpg", 
                "itemName": "Fashion Flower Jewelry Interchangeable Ginger Snap KeyChain & Key Rings Genuine Leather diy making for men and women", 
                "itemWinPromoDto": { }, 
                "itemcode": "252857133", 
                "maxPrice": 2.28, 
                "measureName": "Piece", 
                "minOrder": 20, 
                "minPrice": 1.26, 
                "seoItemName": "fashion-flower-jewelry-interchangeable-ginger", 
                "soldNum": 0
            }, 
            {
                "isfreeShipping": true, 
                "ispromo": false, 
                "itemImgUrl": "http://www.dhresource.com/albu_454347207_00/1.260x260.jpg", 
                "itemName": "Fur Hooded Winter Cloak Princess korean Style Women Poncho Coat Ladies Cape Outerwear cloak mantle cloke 4 colors S,M ,L ,XL ws08", 
                "itemWinPromoDto": { }, 
                "itemcode": "172826513", 
                "maxPrice": 35.23, 
                "measureName": "Piece", 
                "minOrder": 1, 
                "minPrice": 27.6, 
                "seoItemName": "princess-korean-style-women-poncho-fur-hooded", 
                "soldNum": 0
            }, 
            {
                "isfreeShipping": true, 
                "ispromo": false, 
                "itemImgUrl": "http://www.dhresource.com/260x260/f2/albu/g2/M01/0F/B7/rBVaGlSKq8aAez2AAAFc7qIb-Ng579.jpg", 
                "itemName": "AAA Zircon Crystal Earrings mix color 18k copper plated Eco Friendly fashion wedding statement earrings JE05", 
                "itemWinPromoDto": { }, 
                "itemcode": "215025630", 
                "maxPrice": 3.64, 
                "measureName": "Piece", 
                "minOrder": 12, 
                "minPrice": 2.62, 
                "seoItemName": "aaa-zircon-crystal-earrings-mix-color-18k", 
                "soldNum": 0
            }, 
            {
                "isfreeShipping": true, 
                "ispromo": false, 
                "itemImgUrl": "http://www.dhresource.com/albu_450869023_00/1.260x260.jpg", 
                "itemName": "Plus Size Women Sexy Imitated Silk Lingerie Sleepwear Nightdress Robes Lace G String Gown 10pcs lot 6 colors", 
                "itemWinPromoDto": { }, 
                "itemcode": "172474534", 
                "maxPrice": 5.68, 
                "measureName": "Piece", 
                "minOrder": 10, 
                "minPrice": 4.82, 
                "seoItemName": "plus-size-women-sexy-imitated-silk-lingerie", 
                "soldNum": 14
            }, 
            {
                "isfreeShipping": true, 
                "ispromo": false, 
                "itemImgUrl": "http://www.dhresource.com/260x260/f2/albu/g1/M01/50/CB/rBVaGVXS1o6AY2eMAAF6gngI-4s795.jpg", 
                "itemName": "Mix 4 styles Noosa Tassel Earrings Round chunk button Interchangeable diy for men and women Vocheng JewelryE07", 
                "itemWinPromoDto": { }, 
                "itemcode": "251698438", 
                "maxPrice": 2.16, 
                "measureName": "Pair", 
                "minOrder": 20, 
                "minPrice": 1.37, 
                "seoItemName": "mix-4-styles-noosa-tassel-earrings-round", 
                "soldNum": 0
            }, 
            {
                "isfreeShipping": true, 
                "ispromo": false, 
                "itemImgUrl": "http://www.dhresource.com/260x260/f2/albu/g1/M00/4D/4F/rBVaGVYCaBiAZaT6AAHq_ZAuwaI009.jpg", 
                "itemName": "Mix colors Artificial Flower Silk Peach Blossom Peach branch home garden shop wedding decoration Christmas 50pcs lot Christmas decoration", 
                "itemWinPromoDto": { }, 
                "itemcode": "256772762", 
                "maxPrice": 2.94, 
                "measureName": "Piece", 
                "minOrder": 50, 
                "minPrice": 2.41, 
                "seoItemName": "mix-colors-artificial-flower-silk-peach-blossom", 
                "soldNum": 0
            }, 
            {
                "isfreeShipping": true, 
                "ispromo": false, 
                "itemImgUrl": "http://www.dhresource.com/260x260/f2/albu/g2/M00/98/15/rBVaG1YIoxqAY77PAAGTxb89pAY676.jpg", 
                "itemName": "Mix color Artificial Butterfly orchid Blossom flower branch home garden shop wedding decoration Christmas 50pcs lot Christmas decoration", 
                "itemWinPromoDto": { }, 
                "itemcode": "257370899", 
                "maxPrice": 2.94, 
                "measureName": "Piece", 
                "minOrder": 50, 
                "minPrice": 2.41, 
                "seoItemName": "artificial-butterfly-orchid-blossom-flower", 
                "soldNum": 0
            }, 
            {
                "isfreeShipping": true, 
                "ispromo": false, 
                "itemImgUrl": "http://www.dhresource.com/260x260/f2/albu/g2/M00/6F/B3/rBVaG1T30dGALCetAAExyviihl0848.jpg", 
                "itemName": "Mix style foot anklets chains 2015 and can be used bracelet 20pcs lot NE138", 
                "itemWinPromoDto": { }, 
                "itemcode": "230719701", 
                "maxPrice": 1.48, 
                "measureName": "Piece", 
                "minOrder": 20, 
                "minPrice": 1.05, 
                "seoItemName": "mix-style-foot-anklets-chains-2015-and-can", 
                "soldNum": 20
            }, 
            {
                "isfreeShipping": true, 
                "ispromo": false, 
                "itemImgUrl": "http://www.dhresource.com/260x260/f2/albu/g1/M01/58/A1/rBVaGVR4GfuAEoYcAALHxRy7_Kk094.jpg", 
                "itemName": "12 Designs Party Decoration Triangle Flags Cartoon Pennant Frozen princess Cars toys Story Despicable Me Sofia Mickey Minne birthday", 
                "itemWinPromoDto": { }, 
                "itemcode": "214141434", 
                "maxPrice": 2.15, 
                "measureName": "Piece", 
                "minOrder": 10, 
                "minPrice": 1.84, 
                "seoItemName": "12-designs-party-decoration-triangle-flags", 
                "soldNum": 20
            }, 
            {
                "isfreeShipping": true, 
                "ispromo": false, 
                "itemImgUrl": "http://www.dhresource.com/albu_585817881_00/1.260x260.jpg", 
                "itemName": "High quality Mix style 10MM DIY Clay Crystal Shamballa Beads Pave Rhinestone Disco Balls Beads bracelets Necklace loose beads B05", 
                "itemWinPromoDto": { }, 
                "itemcode": "183658835", 
                "maxPrice": 0.26, 
                "measureName": "Piece", 
                "minOrder": 100, 
                "minPrice": 0.19, 
                "seoItemName": "high-quality-mix-style-10mm-diy-clay-crystal", 
                "soldNum": 3
            }, 
            {
                "isfreeShipping": true, 
                "ispromo": false, 
                "itemImgUrl": "http://www.dhresource.com/260x260/f2/albu/g2/M01/1D/11/rBVaGlXaikmAaArxAAHy4Evehxc850.jpg", 
                "itemName": "Mix 8 Style Snap jewelry necklace Crystal Heart dolphins Vocheng pendant necklace with snake chain for christmas gift N65", 
                "itemWinPromoDto": { }, 
                "itemcode": "252439807", 
                "maxPrice": 2.28, 
                "measureName": "Piece", 
                "minOrder": 24, 
                "minPrice": 1.37, 
                "seoItemName": "mix-8-style-snap-jewelry-necklace-crystal", 
                "soldNum": 0
            }, 
            {
                "isfreeShipping": true, 
                "ispromo": false, 
                "itemImgUrl": "http://www.dhresource.com/260x260/f2/albu/g1/M01/45/29/rBVaGFXHCZuADsOuAAGulwvguFI078.jpg", 
                "itemName": "Despicable Me minions Photo Glass Cabochon Floating Charms Pendant Necklace Locket Chains Jewelry Christmas Gift NE170", 
                "itemWinPromoDto": { }, 
                "itemcode": "250643282", 
                "maxPrice": 1.94, 
                "measureName": "Piece", 
                "minOrder": 20, 
                "minPrice": 1.37, 
                "seoItemName": "despicable-me-minions-photo-glass-cabochon", 
                "soldNum": 0
            }, 
            {
                "isfreeShipping": true, 
                "ispromo": false, 
                "itemImgUrl": "http://www.dhresource.com/260x260/f2/albu/g3/M00/BD/69/rBVaHFXME0WARBgVAAGIKpRu6h4633.jpg", 
                "itemName": "Mix 6 desgin Crystal owls Tortoise Snap Jewelry Necklace Snake Chain Round Silver Tone Clear Rhinestone Ginger necklace", 
                "itemWinPromoDto": { }, 
                "itemcode": "251148670", 
                "maxPrice": 2.5, 
                "measureName": "Piece", 
                "minOrder": 20, 
                "minPrice": 1.37, 
                "seoItemName": "mix-6-desgin-crystal-owls-tortoise-snap-jewelry", 
                "soldNum": 0
            }, 
            {
                "isfreeShipping": true, 
                "ispromo": false, 
                "itemImgUrl": "http://www.dhresource.com/260x260/f2/albu/g1/M00/C8/63/rBVaGFWbPyGAYWYxAAE1RCPnDWE377.jpg", 
                "itemName": "Mix style Clovers gold plated multicolor dried flower round pendant Clover floating locket charms necklace pendant for woman gift FL11", 
                "itemWinPromoDto": { }, 
                "itemcode": "245980110", 
                "maxPrice": 3.64, 
                "measureName": "Piece", 
                "minOrder": 12, 
                "minPrice": 2.94, 
                "seoItemName": "mix-style-clovers-gold-plated-multicolor", 
                "soldNum": 0
            }, 
            {
                "isfreeShipping": true, 
                "ispromo": false, 
                "itemImgUrl": "http://www.dhresource.com/260x260/f2/albu/g2/M01/30/30/rBVaG1Xv9KOAc03eAAJI0lUJJWk274.jpg", 
                "itemName": "Mix 10 styles Silver Tone Christmas White Snowman Pendant Snap Button Jewelry diy Necklace (fit 18mm 20mm snap with snake Chain", 
                "itemWinPromoDto": { }, 
                "itemcode": "254777115", 
                "maxPrice": 22.73, 
                "measureName": "Piece", 
                "minOrder": 10, 
                "minPrice": 18.85, 
                "seoItemName": "mix-10-styles-silver-tone-christmas-white", 
                "soldNum": 0
            }, 
            {
                "isfreeShipping": true, 
                "ispromo": false, 
                "itemImgUrl": "http://www.dhresource.com/albu_432766113_00/1.260x260.jpg", 
                "itemName": "handcuffs bracelet with ceramic beads and crystal wrap geniune brown leather bracelet 20PCs lot Adjustable Rope Jewelry Y0033", 
                "itemWinPromoDto": { }, 
                "itemcode": "170778356", 
                "maxPrice": 2.27, 
                "measureName": "Piece", 
                "minOrder": 20, 
                "minPrice": 1.78, 
                "seoItemName": "handcuffs-bracelet-with-ceramic-beads-and", 
                "soldNum": 0
            }, 
            {
                "isfreeShipping": true, 
                "ispromo": false, 
                "itemImgUrl": "http://www.dhresource.com/260x260/f2/albu/g2/M00/36/48/rBVaGlXa40aAT93WAADJsxjAsMY459.jpg", 
                "itemName": "Choose NOOSA Metal Bracelet Vintage Silver indian jewelry Snap Button Cuff Bracelet Interchangeable Jewelry Ginger Snaps Silver JewelryN376", 
                "itemWinPromoDto": { }, 
                "itemcode": "252478663", 
                "maxPrice": 4.55, 
                "measureName": "Piece", 
                "minOrder": 10, 
                "minPrice": 3.36, 
                "seoItemName": "choose-noosa-metal-bracelet-vintage-silver", 
                "soldNum": 0
            }, 
            {
                "isfreeShipping": true, 
                "ispromo": false, 
                "itemImgUrl": "http://www.dhresource.com/260x260/f2/albu/g3/M01/22/EB/rBVaHVYIoTyAeDxSAAFucuenw-A537.jpg", 
                "itemName": "Artificial Flower Silk Peach Blossom Peach branch home garden shop wedding decoration Christmas 100pcs lot Christmas decoration", 
                "itemWinPromoDto": { }, 
                "itemcode": "257369497", 
                "maxPrice": 2.83, 
                "measureName": "Piece", 
                "minOrder": 100, 
                "minPrice": 2.41, 
                "seoItemName": "artificial-flower-silk-peach-blossom-peach", 
                "soldNum": 0
            }, 
            {
                "isfreeShipping": true, 
                "ispromo": false, 
                "itemImgUrl": "http://www.dhresource.com/260x260/f2/albu/g2/M00/04/84/rBVaGlYIt7yAQBfkAAFpqJLvu88797.jpg", 
                "itemName": "3D Sea World Wall Stickers Finding Nemo Submarine World Decorative Wall Decal Cartoon Wallpaper Kids Party Decoration Christmas Wall", 
                "itemWinPromoDto": { }, 
                "itemcode": "257382519", 
                "maxPrice": 5.66, 
                "measureName": "Piece", 
                "minOrder": 10, 
                "minPrice": 4.19, 
                "seoItemName": "3d-sea-world-wall-stickers-submarine-world", 
                "soldNum": 0
            }, 
            {
                "isfreeShipping": true, 
                "ispromo": true, 
                "itemImgUrl": "http://www.dhresource.com/260x260/f2/albu/g2/M00/F8/75/rBVaG1SczjaAHIrEAAGtQu_6Zks582.jpg", 
                "itemName": "Handmade Children's Knitted Caps Crochet Frozen Olaf Hat Infant Toddler Hats Kids Winter Beanie Skullcap Earflaps S-XXL for choose BA146", 
                "itemWinPromoDto": {
                    "discountRate": 10, 
                    "dynamicType": 1, 
                    "promoMaxPrice": 4.5, 
                    "promoMinPrice": 3.02, 
                    "promoTypeId": 0, 
                    "promoclass": "off-ico2"
                }, 
                "itemcode": "215968215", 
                "maxPrice": 5, 
                "measureName": "Piece", 
                "minOrder": 10, 
                "minPrice": 3.36, 
                "seoItemName": "handmade-children-039-s-knitted-caps-crochet", 
                "soldNum": 80
            }, 
            {
                "isfreeShipping": true, 
                "ispromo": false, 
                "itemImgUrl": "http://www.dhresource.com/260x260/f2/albu/g2/M01/F6/C1/rBVaG1Xs31aAXpWTAAF_WpHg5Ns931.jpg", 
                "itemName": "Infinity Elephant heart snap leather bracelet styles choose friendship Snap jewelry for gift customs diy making", 
                "itemWinPromoDto": { }, 
                "itemcode": "254372860", 
                "maxPrice": 2.05, 
                "measureName": "Piece", 
                "minOrder": 10, 
                "minPrice": 1.37, 
                "seoItemName": "infinity-elephant-heart-snap-leather-bracelet", 
                "soldNum": 0
            }, 
            {
                "isfreeShipping": true, 
                "ispromo": false, 
                "itemImgUrl": "http://www.dhresource.com/albu_462475455_00/1.260x260.jpg", 
                "itemName": "xmas decoration santa sacks Merry Christmas Red Socks Stockings gift bag 100pcs lot SE05", 
                "itemWinPromoDto": { }, 
                "itemcode": "173528816", 
                "maxPrice": 1.19, 
                "measureName": "Piece", 
                "minOrder": 100, 
                "minPrice": 0.69, 
                "seoItemName": "xmas-decoration-santa-sacks-merry-christmas", 
                "soldNum": 0
            }
        ], 
        "totalRecord": 2623
    }, 
    "message": "Success", 
    "serverTime": 1447652943693, 
    "state": "0x0000"
}