//新人专享大礼包页面依赖的公用业务功能模块
$IMPORT('src/common/checkoutflow/popupTip.js');
$IMPORT('src/common/checkoutflow/dataErrorLog.js');
$IMPORT('src/common/tools/jquery.cookie.js');
//新人专享大礼包依赖的公用业务功能模块
$IMPORT('src/common/config.js');
$IMPORT('src/common/langLoader.js');
//新人专享大礼包页面模板
$IMPORT('src/newUserCoupons/tpl/newUserCouponTpl.js');
//提示用户更新完领取新人大礼包页面功能模块
$IMPORT('src/newUserCoupons/updateForNew.js');
//新人专享大礼包页面功能模块
$IMPORT('src/newUserCoupons/newUserCouponState.js');
$IMPORT('src/newUserCoupons/bindCouponPackage.js');
$IMPORT('src/newUserCoupons/index.js');
$IMPORT('src/newUserCoupons/main.js');