$axure.loadCurrentPage({
  "url":"vip的位置.html",
  "generationDate":new Date(1451376400989.58),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"1bb17a39ca5a4f278f9c3ced1e79b80e",
    "type":"Axure:Page",
    "name":"VIP的位置",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"7cf01fd3dae747aba3bdc89e70fd29ab",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":18,
              "y":24},
            "size":{
              "width":367,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a1a9358af1434e39af7e26f718dc7068",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":18,
                  "y":24},
                "size":{
                  "width":367,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"60ae12cc174d477c83051c605c3fbe38",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":18,
              "y":74},
            "size":{
              "width":492,
              "height":207},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6e449b041a6643678ec6a7815e6fab11",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":18,
                  "y":74},
                "size":{
                  "width":492,
                  "height":207},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/vip的位置/u2.png"}},
{
          "id":"fe11a95a4d7f44459d6990a7a2442cbe",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":18,
              "y":346},
            "size":{
              "width":492,
              "height":669},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d2b488d1c4049d1bbe234746485ff90",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":18,
                  "y":346},
                "size":{
                  "width":492,
                  "height":669},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/vip的位置/u4.png"}},
{
          "id":"42b589ae355b4116a7abd3bca6b1f15f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":234,
              "y":945},
            "size":{
              "width":50,
              "height":60},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"570faf5117fb4a28b261528bb66ffcdd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":234,
                  "y":945},
                "size":{
                  "width":50,
                  "height":60},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/vip的位置/u6.png"}},
{
          "id":"fbcb16f8d35540a49a1920296b3021b9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":255,
              "y":959},
            "size":{
              "width":21,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1173967a9dd45749db8e246d34f7668",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":255,
                  "y":959},
                "size":{
                  "width":21,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/__deals____vip_club___/u6.png"}},
{
          "id":"c6e4ee40542d418eabd28fd71602dcf2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":249,
              "y":989},
            "size":{
              "width":34,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24e72862811540dbb62fc8bbfa2972d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":249,
                  "y":989},
                "size":{
                  "width":34,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bf85c8e6c96f4f72a6c64d39c6f3d4cc",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":22,
              "y":346},
            "size":{
              "width":480,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/vip的位置/u12_line.png"}},
{
          "id":"9546b06ad8684eb7add42502e081fb53",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":22,
              "y":725},
            "size":{
              "width":480,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/vip的位置/u12_line.png"}},
{
          "id":"ac4445884bc64cddb30de14e7b8d32a7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"19px",
            "location":{
              "x":90,
              "y":305},
            "size":{
              "width":89,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"de9650047bf34015a23f936bb07c86f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"19px",
                "location":{
                  "x":90,
                  "y":305},
                "size":{
                  "width":89,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ed29e779367d47358d2c8cfd4e7641aa",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":33,
              "y":296.5},
            "size":{
              "width":47,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"86b8e3225fee4e81a990a33b58e7b382",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":33,
                  "y":296.5},
                "size":{
                  "width":47,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/vip的位置/u16.png"}},
{
          "id":"b23e404f9a25423a8b6714a2b1cb0a49",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":528,
              "y":308},
            "size":{
              "width":78,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"29b1804902244b4bb65536f4f4244866",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":528,
                  "y":308},
                "size":{
                  "width":78,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eb1992fa2c6c48ca83967aa2c645e123",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":651,
              "y":60},
            "size":{
              "width":489,
              "height":203},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c7cc13ca26d14854b50f9e43027b0649",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":651,
                  "y":60},
                "size":{
                  "width":489,
                  "height":203},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/vip的位置/u20.png"}},
{
          "id":"4d4b430617fc461d860027d24df48093",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":650,
              "y":336},
            "size":{
              "width":489,
              "height":667},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"109923134f4a4263990ca8ea67f284dc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":650,
                  "y":336},
                "size":{
                  "width":489,
                  "height":667},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/vip的位置/u22.png"}},
{
          "id":"ad6bbfd4b33f49c4a5af108f318cdbfc",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":655,
              "y":331},
            "size":{
              "width":480,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/vip的位置/u12_line.png"}},
{
          "id":"9b24f0ab7ea84d54ba4126a092aef23a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"19px",
            "location":{
              "x":723,
              "y":290},
            "size":{
              "width":89,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c235b8d2cd74d3faabc00af59a77756",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"19px",
                "location":{
                  "x":723,
                  "y":290},
                "size":{
                  "width":89,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"112ca417288a404c94f50ace55c43182",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":665,
              "y":281},
            "size":{
              "width":47,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d599250445c45d99fb43a2abd0fdc9e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":665,
                  "y":281},
                "size":{
                  "width":47,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/vip的位置/u16.png"}},
{
          "id":"17bce9c5a9e4482daa3618fa5dc2731d",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":655,
              "y":716},
            "size":{
              "width":480,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/vip的位置/u12_line.png"}},
{
          "id":"dfc7d66334c34e34b54cc38a8068fa7d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":528,
              "y":340},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e63ecb2755714c2cbbedb8055a609955",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":528,
                  "y":340},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b619ca0299234e4aa8e6ab98e57ee23d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":870,
              "y":936},
            "size":{
              "width":50,
              "height":60},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aa6a4583ffb147488bbf453ef3763d8a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":870,
                  "y":936},
                "size":{
                  "width":50,
                  "height":60},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/vip的位置/u6.png"}},
{
          "id":"f9c89ff684e94b39a6533b4285cfb0db",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":891,
              "y":948},
            "size":{
              "width":21,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"41a5a13412c74599aca47f6e102c1b2c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":891,
                  "y":948},
                "size":{
                  "width":21,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/__deals____vip_club___/u6.png"}},
{
          "id":"de1a3249f32e4d2b88ef4377fbf84739",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":885,
              "y":978},
            "size":{
              "width":34,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a50bb9975c04399981349825df5b5f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":885,
                  "y":978},
                "size":{
                  "width":34,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "7cf01fd3dae747aba3bdc89e70fd29ab":{
      "scriptId":"u0"},
    "a1a9358af1434e39af7e26f718dc7068":{
      "scriptId":"u1"},
    "60ae12cc174d477c83051c605c3fbe38":{
      "scriptId":"u2"},
    "6e449b041a6643678ec6a7815e6fab11":{
      "scriptId":"u3"},
    "fe11a95a4d7f44459d6990a7a2442cbe":{
      "scriptId":"u4"},
    "1d2b488d1c4049d1bbe234746485ff90":{
      "scriptId":"u5"},
    "42b589ae355b4116a7abd3bca6b1f15f":{
      "scriptId":"u6"},
    "570faf5117fb4a28b261528bb66ffcdd":{
      "scriptId":"u7"},
    "fbcb16f8d35540a49a1920296b3021b9":{
      "scriptId":"u8"},
    "d1173967a9dd45749db8e246d34f7668":{
      "scriptId":"u9"},
    "c6e4ee40542d418eabd28fd71602dcf2":{
      "scriptId":"u10"},
    "24e72862811540dbb62fc8bbfa2972d3":{
      "scriptId":"u11"},
    "bf85c8e6c96f4f72a6c64d39c6f3d4cc":{
      "scriptId":"u12"},
    "9546b06ad8684eb7add42502e081fb53":{
      "scriptId":"u13"},
    "ac4445884bc64cddb30de14e7b8d32a7":{
      "scriptId":"u14"},
    "de9650047bf34015a23f936bb07c86f2":{
      "scriptId":"u15"},
    "ed29e779367d47358d2c8cfd4e7641aa":{
      "scriptId":"u16"},
    "86b8e3225fee4e81a990a33b58e7b382":{
      "scriptId":"u17"},
    "b23e404f9a25423a8b6714a2b1cb0a49":{
      "scriptId":"u18"},
    "29b1804902244b4bb65536f4f4244866":{
      "scriptId":"u19"},
    "eb1992fa2c6c48ca83967aa2c645e123":{
      "scriptId":"u20"},
    "c7cc13ca26d14854b50f9e43027b0649":{
      "scriptId":"u21"},
    "4d4b430617fc461d860027d24df48093":{
      "scriptId":"u22"},
    "109923134f4a4263990ca8ea67f284dc":{
      "scriptId":"u23"},
    "ad6bbfd4b33f49c4a5af108f318cdbfc":{
      "scriptId":"u24"},
    "9b24f0ab7ea84d54ba4126a092aef23a":{
      "scriptId":"u25"},
    "7c235b8d2cd74d3faabc00af59a77756":{
      "scriptId":"u26"},
    "112ca417288a404c94f50ace55c43182":{
      "scriptId":"u27"},
    "9d599250445c45d99fb43a2abd0fdc9e":{
      "scriptId":"u28"},
    "17bce9c5a9e4482daa3618fa5dc2731d":{
      "scriptId":"u29"},
    "dfc7d66334c34e34b54cc38a8068fa7d":{
      "scriptId":"u30"},
    "e63ecb2755714c2cbbedb8055a609955":{
      "scriptId":"u31"},
    "b619ca0299234e4aa8e6ab98e57ee23d":{
      "scriptId":"u32"},
    "aa6a4583ffb147488bbf453ef3763d8a":{
      "scriptId":"u33"},
    "f9c89ff684e94b39a6533b4285cfb0db":{
      "scriptId":"u34"},
    "41a5a13412c74599aca47f6e102c1b2c":{
      "scriptId":"u35"},
    "de1a3249f32e4d2b88ef4377fbf84739":{
      "scriptId":"u36"},
    "0a50bb9975c04399981349825df5b5f0":{
      "scriptId":"u37"}}});