//directFlowToApp页依赖的公用tools
$IMPORT('src/common/tools/jquery.cookie.js');
//directFlowToApp页依赖的公用业务功能模块
$IMPORT('src/common/config.js');
$IMPORT('src/common/langLoader.js');
//directFlowToApp页模板
$IMPORT('src/directFlowToApp/tpl/directFlowToAppTpl.js');
//mycoupon页功能模块
$IMPORT('src/directFlowToApp/directFlowToApp.js');
$IMPORT('src/directFlowToApp/index.js');
$IMPORT('src/directFlowToApp/main.js');