//mycoupon页依赖的公用tools
$IMPORT('src/common/tools/fastclick.js');
$IMPORT('src/common/tools/jquery.cookie.js');
$IMPORT('src/common/tools/deeplink.js');
//mycoupon页依赖的公用业务功能模块
$IMPORT('src/common/config.js');
$IMPORT('src/common/langLoader.js');
$IMPORT('src/common/appopen.js');
$IMPORT('src/common/checkoutflow/dataErrorLog.js');
$IMPORT('src/common/checkoutflow/popupTip.js');
$IMPORT('src/common/mydhgate/ifLogIn.js');
//mycoupon页模板
$IMPORT('src/mycoupon/tpl/getCouponListTpl.js');
$IMPORT('src/mycoupon/tpl/addCouponTpl.js');
//mycoupon页功能模块
$IMPORT('src/mycoupon/getCouponList.js');
$IMPORT('src/mycoupon/addCoupon.js');
$IMPORT('src/mycoupon/searchCouponNum.js');
$IMPORT('src/mycoupon/gotoTop.js');
$IMPORT('src/mycoupon/openMycouponApp.js');
$IMPORT('src/mycoupon/index.js');
$IMPORT('src/mycoupon/main.js');