//placeOrder依赖的公用tools
$IMPORT('src/common/tools/fastclick.js');
$IMPORT('src/common/tools/jquery.cookie.js');
//placeOrder依赖的公用业务功能模块
$IMPORT('src/common/config.js');
$IMPORT('src/common/langLoader.js');
$IMPORT('src/common/checkoutflow/dataErrorLog.js');
$IMPORT('src/common/checkoutflow/getCountrysData.js');
$IMPORT('src/common/checkoutflow/getStatesData.js');
$IMPORT('src/common/checkoutflow/getUserInfo.js');
$IMPORT('src/common/checkoutflow/popupTip.js');
$IMPORT('src/common/checkoutflow/regexpConfig.js');
$IMPORT('src/common/checkoutflow/thirdPartyCode.js');
//placeOrder模板
$IMPORT('src/placeOrder/tpl/placeOrderTpl.js');
$IMPORT('src/placeOrder/tpl/shipAddressTpl.js');
$IMPORT('src/placeOrder/tpl/editshipAddressTpl.js');
//placeOrder功能模块
$IMPORT('src/placeOrder/lazyload.js');
$IMPORT('src/placeOrder/unbindCoupon.js');
$IMPORT('src/placeOrder/addCouponInfo.js');
$IMPORT('src/placeOrder/couponList.js');
$IMPORT('src/placeOrder/editShipAddress.js');
$IMPORT('src/placeOrder/email.js');
$IMPORT('src/placeOrder/getCouponInfo.js');
$IMPORT('src/placeOrder/getPlaceOrder.js');
$IMPORT('src/placeOrder/getShippingAddressList.js');
$IMPORT('src/placeOrder/placeOrderBtn.js');
$IMPORT('src/placeOrder/placeOrderupDateCart.js');
$IMPORT('src/placeOrder/remark.js');
$IMPORT('src/placeOrder/saveEditAddress.js');
$IMPORT('src/placeOrder/selectShipAddress.js');
$IMPORT('src/placeOrder/shipAddress.js');
$IMPORT('src/placeOrder/shippingList.js');
$IMPORT('src/placeOrder/userVisitor.js');
$IMPORT('src/placeOrder/placeOrder.js');
$IMPORT('src/placeOrder/index.js');
$IMPORT('src/placeOrder/main.js');