/**
 * module src: home/tpl/youMyLikeTpl.js
 * 猜你喜欢的推荐产品模板
**/
define('appTpl/youMyLikeTpl', [], function(){
    return [
        '<% var data = obj.list, len = data.length;%>',
        '<% if (len !== 0) { %>',
            '<div class="viewed-box">',
                '<div class="viewed-tit"><%=$.lang["Youmaylike"]%></div>',
                '<div class="viewed-list">',
                    '<ul>',
                        '<% for (var i = 0; i < len; i++) { %>',
                            '<% if (i<=5) { %>',
                                '<li>',
                                    '<a rel="nofollow" href="<%=data[i]["proUrl"]%>">',
                                        '<div class="pro-img hasload">',
                                            '<% if (data[i]["discountType"]==="0") {%><span class="off-ico2"><%=$.lang.replaceTplVar("COMMON_Discount_0", {val: data[i]["discountRate"]})%></span><% } %>',
                                            '<% if (data[i]["discountType"]==="1") {%><span class="reduction-ico"><%=$.lang.replaceTplVar("COMMON_Discount_1", {val: data[i]["discountRate"]})%></span><% } %>',
                                            '<img src="<%=data[i]["imgUrl"]%>">',
                                        '</div>',
                                        '<div class="pro-text">',
                                            '<p class="pro-piece"><strong><% if (data[i]["appExclusive"]==="1") {%> <b class="mobile-deals"></b><% } %>',
                                                '<% if (obj.countryCur==="ru" || obj.countryCur==="tr") { %>',
                                                    '<%=data[i]["price"]%> <%=obj.currencyText%>',
                                                '<% } else { %>',
                                                     '<%=obj.currencyText%><%=data[i]["price"]%>',
                                                '<% } %>',
                                             '</strong></p>',
                                        '</div>',
                                    '</a>',
                                '</li>',
                            '<% }else{ %>',
                                '<% if (i<20) { %>',
                                    '<li>',
                                        '<a rel="nofollow" href="<%=data[i]["proUrl"]%>">',
                                            '<div class="pro-img">',
                                                '<% if (data[i]["discountType"]==="0") {%><span class="off-ico2"><%=$.lang.replaceTplVar("COMMON_Discount_0", {val: data[i]["discountRate"]})%></span><% } %>',
                                                '<% if (data[i]["discountType"]==="1") {%><span class="reduction-ico"><%=$.lang.replaceTplVar("COMMON_Discount_1", {val: data[i]["discountRate"]})%></span><% } %>',
                                                '<img src="" class="lazy" data-original="<%=data[i]["imgUrl"]%>">',
                                            '</div>',
                                            '<div class="pro-text">',
                                                '<p class="pro-piece"><strong><% if (data[i]["appExclusive"]==="1") {%> <b class="mobile-deals"></b><% } %>',
                                                    '<% if (obj.countryCur==="ru" || obj.countryCur==="tr") { %>',
                                                        '<%=data[i]["price"]%> <%=obj.currencyText%>',
                                                    '<% } else { %>',
                                                        '<%=obj.currencyText%><%=data[i]["price"]%>',
                                                    '<% } %>',
                                                '</strong></p>',
                                            '</div>',
                                        '</a>',
                                    '</li>',
                                '<% } else { %>',
                                    '<li style="display:none;">',
                                        '<a rel="nofollow" href="<%=data[i]["proUrl"]%>">',
                                            '<div class="pro-img">',
                                                '<% if (data[i]["discountType"]==="0") {%><span class="off-ico2"><%=$.lang.replaceTplVar("COMMON_Discount_0", {val: data[i]["discountRate"]})%></span><% } %>',
                                                '<% if (data[i]["discountType"]==="1") {%><span class="reduction-ico"><%=$.lang.replaceTplVar("COMMON_Discount_1", {val: data[i]["discountRate"]})%></span><% } %>',
                                                '<img src="" class="lazy" data-original="<%=data[i]["imgUrl"]%>">',
                                            '</div>',
                                            '<div class="pro-text">',
                                                '<p class="pro-piece"><strong><% if (data[i]["appExclusive"]==="1") {%> <b class="mobile-deals"></b><% } %>',
                                                    '<% if (obj.countryCur==="ru" || obj.countryCur==="tr") { %>',
                                                        '<%=data[i]["price"]%> <%=obj.currencyText%>',
                                                    '<% } else { %>',
                                                         '<%=obj.currencyText%><%=data[i]["price"]%>',
                                                    '<% } %>',
                                                '</strong></p>',
                                            '</div>',
                                        '</a>',
                                    '</li>',
                                '<% } %>',
                            '<% } %>',
                        '<% } %>',
                    '</ul>',
                '</div>',
                '<% if (len>20) { %>',
                    '<a rel="nofollow" class="more j-youMyLikeMore" href="javascript:;" onclick="javascript:ga(\'send\', \'event\', \'MHP\', \'Show more\')"><%=$.lang["Show_more"]%></a>',
                '<% } %>',
            '</div>',
        '<% } %>'
    ];
});
