{
    "data": {
        "currencyText": "US $",
        "page": {
            "currentRecord": 1,
            "endNo": 16,
            "nextPageNo": 1,
            "pageNum": 1,
            "pageSize": 16,
            "pages": 1,
            "prePageNo": 1,
            "startNo": 1,
            "totalPage": 1,
            "totalRecord": 16
        },
        "resultList": [
            {
                "discountPrice": "",
                "discountRate": 5,
                "imgUrl": "http://www.dhresource.com/albu_888521956_00/1.0x0.jpg",
                "itemCode": "206996950",
                "maxPrice": 2.78,
                "minPrice": 2.57,
                "originalPrice": 2.64,
                "promoType": "0",
                "seoName": "fine-decor-wallpaper-roll-modern-natural",
                "supplierId": "ff80808131adf1ce0131bdedbf443213",
                "title": "Wholesale - Fine decor wallpaper roll Modern natural rustic grey/red Brick stone wall wallpaper hotel background wall decor pvc wallpaper",
                "minOrder": 7,
                "lots": "7Piece/Lot",
                "measure": "Piece"
            },
            {
                "discountPrice": "2.64",
                "discountRate": 5,
                "imgUrl": "http://www.dhresource.com/albu_888521956_00/1.0x0.jpg",
                "itemCode": "206996950",
                "maxPrice": 2.78,
                "minPrice": 2.57,
                "originalPrice": 2.64,
                "promoType": "10",
                "seoName": "fine-decor-wallpaper-roll-modern-natural",
                "supplierId": "ff80808131adf1ce0131bdedbf443213",
                "title": "Wholesale - Fine decor wallpaper roll Modern natural rustic grey/red Brick stone wall wallpaper hotel background wall decor pvc wallpaper",
                "minOrder": 7,
                "lots": "7Piece/Lot",
                "measure": "Piece"
            },
            {
                "discountPrice": "2.64",
                "discountRate": 5,
                "imgUrl": "http://www.dhresource.com/albu_888521956_00/1.0x0.jpg",
                "itemCode": "206996950",
                "maxPrice": 2.78,
                "minPrice": 2.57,
                "originalPrice": 2.64,
                "promoType": "20",
                "seoName": "fine-decor-wallpaper-roll-modern-natural",
                "supplierId": "ff80808131adf1ce0131bdedbf443213",
                "title": "Wholesale - Fine decor wallpaper roll Modern natural rustic grey/red Brick stone wall wallpaper hotel background wall decor pvc wallpaper",
                "minOrder": 7,
                "lots": "7Piece/Lot",
                "measure": "Piece"
            },
            {
                "discountPrice": "2.64",
                "discountRate": 5,
                "imgUrl": "http://www.dhresource.com/albu_888521956_00/1.0x0.jpg",
                "itemCode": "206996950",
                "maxPrice": 2.78,
                "minPrice": 2.57,
                "originalPrice": 2.64,
                "promoType": "30",
                "seoName": "fine-decor-wallpaper-roll-modern-natural",
                "supplierId": "ff80808131adf1ce0131bdedbf443213",
                "title": "Wholesale - Fine decor wallpaper roll Modern natural rustic grey/red Brick stone wall wallpaper hotel background wall decor pvc wallpaper",
                "minOrder": 7,
                "lots": "7Piece/Lot",
                "measure": "Piece"
            },
            {
                "discountPrice": "2.64",
                "discountRate": 5,
                "imgUrl": "http://www.dhresource.com/albu_888521956_00/1.0x0.jpg",
                "itemCode": "206996950",
                "maxPrice": 2.78,
                "minPrice": 2.57,
                "originalPrice": 2.64,
                "promoType": "40",
                "seoName": "fine-decor-wallpaper-roll-modern-natural",
                "supplierId": "ff80808131adf1ce0131bdedbf443213",
                "title": "Wholesale - Fine decor wallpaper roll Modern natural rustic grey/red Brick stone wall wallpaper hotel background wall decor pvc wallpaper",
                "minOrder": 7,
                "lots": "7Piece/Lot",
                "measure": "Piece"
            },
            {
                "discountPrice": "2.64",
                "discountRate": 5,
                "imgUrl": "http://www.dhresource.com/albu_888521956_00/1.0x0.jpg",
                "itemCode": "206996950",
                "maxPrice": 2.78,
                "minPrice": 2.57,
                "originalPrice": 2.64,
                "promoType": "50",
                "seoName": "fine-decor-wallpaper-roll-modern-natural",
                "supplierId": "ff80808131adf1ce0131bdedbf443213",
                "title": "Wholesale - Fine decor wallpaper roll Modern natural rustic grey/red Brick stone wall wallpaper hotel background wall decor pvc wallpaper",
                "minOrder": 7,
                "lots": "7Piece/Lot",
                "measure": "Piece"
            },
            {
                "discountPrice": "2.64",
                "discountRate": 5,
                "imgUrl": "http://www.dhresource.com/albu_888521956_00/1.0x0.jpg",
                "itemCode": "206996950",
                "maxPrice": 2.78,
                "minPrice": 2.57,
                "originalPrice": 2.64,
                "promoType": "60",
                "seoName": "fine-decor-wallpaper-roll-modern-natural",
                "supplierId": "ff80808131adf1ce0131bdedbf443213",
                "title": "Wholesale - Fine decor wallpaper roll Modern natural rustic grey/red Brick stone wall wallpaper hotel background wall decor pvc wallpaper",
                "minOrder": 7,
                "lots": "7Piece/Lot",
                "measure": "Piece"
            },
            {
                "discountPrice": "2.64",
                "discountRate": 5,
                "imgUrl": "http://www.dhresource.com/albu_888521956_00/1.0x0.jpg",
                "itemCode": "206996950",
                "maxPrice": 2.78,
                "minPrice": 2.57,
                "originalPrice": 2.64,
                "promoType": "70",
                "seoName": "fine-decor-wallpaper-roll-modern-natural",
                "supplierId": "ff80808131adf1ce0131bdedbf443213",
                "title": "Wholesale - Fine decor wallpaper roll Modern natural rustic grey/red Brick stone wall wallpaper hotel background wall decor pvc wallpaper",
                "minOrder": 7,
                "lots": "7Piece/Lot",
                "measure": "Piece"
            },
            {
                "discountPrice": "2.64",
                "discountRate": 5,
                "imgUrl": "http://www.dhresource.com/albu_888521956_00/1.0x0.jpg",
                "itemCode": "206996950",
                "maxPrice": 2.78,
                "minPrice": 2.57,
                "originalPrice": 2.64,
                "promoType": "80",
                "seoName": "fine-decor-wallpaper-roll-modern-natural",
                "supplierId": "ff80808131adf1ce0131bdedbf443213",
                "title": "Wholesale - Fine decor wallpaper roll Modern natural rustic grey/red Brick stone wall wallpaper hotel background wall decor pvc wallpaper",
                "minOrder": 7,
                "lots": "7Piece/Lot",
                "measure": "Piece"
            },
            {
                "discountPrice": "2.64",
                "discountRate": 5,
                "imgUrl": "http://www.dhresource.com/albu_888521956_00/1.0x0.jpg",
                "itemCode": "206996950",
                "maxPrice": 2.78,
                "minPrice": 2.57,
                "originalPrice": 2.64,
                "promoType": "90",
                "seoName": "fine-decor-wallpaper-roll-modern-natural",
                "supplierId": "ff80808131adf1ce0131bdedbf443213",
                "title": "Wholesale - Fine decor wallpaper roll Modern natural rustic grey/red Brick stone wall wallpaper hotel background wall decor pvc wallpaper",
                "minOrder": 7,
                "lots": "7Piece/Lot",
                "measure": "Piece"
            },
            {
                "discountPrice": "2.64",
                "discountRate": 5,
                "imgUrl": "http://www.dhresource.com/albu_888521956_00/1.0x0.jpg",
                "itemCode": "206996950",
                "maxPrice": 2.78,
                "minPrice": 2.57,
                "originalPrice": 2.64,
                "promoType": "100",
                "seoName": "fine-decor-wallpaper-roll-modern-natural",
                "supplierId": "ff80808131adf1ce0131bdedbf443213",
                "title": "Wholesale - Fine decor wallpaper roll Modern natural rustic grey/red Brick stone wall wallpaper hotel background wall decor pvc wallpaper",
                "minOrder": 7,
                "lots": "7Piece/Lot",
                "measure": "Piece"
            },
            {
                "discountPrice": "2.64",
                "discountRate": 5,
                "imgUrl": "http://www.dhresource.com/albu_888521956_00/1.0x0.jpg",
                "itemCode": "206996950",
                "maxPrice": 2.78,
                "minPrice": 2.57,
                "originalPrice": 2.64,
                "promoType": "0",
                "seoName": "fine-decor-wallpaper-roll-modern-natural",
                "supplierId": "ff80808131adf1ce0131bdedbf443213",
                "title": "Wholesale - Fine decor wallpaper roll Modern natural rustic grey/red Brick stone wall wallpaper hotel background wall decor pvc wallpaper",
                "minOrder": 7,
                "lots": "7Piece/Lot",
                "measure": "Piece"
            },
            {
                "discountPrice": "2.64",
                "discountRate": 5,
                "imgUrl": "http://www.dhresource.com/albu_888521956_00/1.0x0.jpg",
                "itemCode": "206996950",
                "maxPrice": 2.78,
                "minPrice": 2.57,
                "originalPrice": 2.64,
                "promoType": "10",
                "seoName": "fine-decor-wallpaper-roll-modern-natural",
                "supplierId": "ff80808131adf1ce0131bdedbf443213",
                "title": "Wholesale - Fine decor wallpaper roll Modern natural rustic grey/red Brick stone wall wallpaper hotel background wall decor pvc wallpaper",
                "minOrder": 7,
                "lots": "7Piece/Lot",
                "measure": "Piece"
            },
            {
                "discountPrice": "2.64",
                "discountRate": 5,
                "imgUrl": "http://www.dhresource.com/albu_888521956_00/1.0x0.jpg",
                "itemCode": "206996950",
                "maxPrice": 2.78,
                "minPrice": 2.57,
                "originalPrice": 2.64,
                "promoType": "20",
                "seoName": "fine-decor-wallpaper-roll-modern-natural",
                "supplierId": "ff80808131adf1ce0131bdedbf443213",
                "title": "Wholesale - Fine decor wallpaper roll Modern natural rustic grey/red Brick stone wall wallpaper hotel background wall decor pvc wallpaper",
                "minOrder": 7,
                "lots": "7Piece/Lot",
                "measure": "Piece"
            },
            {
                "discountPrice": "2.64",
                "discountRate": 5,
                "imgUrl": "http://www.dhresource.com/albu_888521956_00/1.0x0.jpg",
                "itemCode": "206996950",
                "maxPrice": 2.78,
                "minPrice": 2.57,
                "originalPrice": 2.64,
                "promoType": "30",
                "seoName": "fine-decor-wallpaper-roll-modern-natural",
                "supplierId": "ff80808131adf1ce0131bdedbf443213",
                "title": "Wholesale - Fine decor wallpaper roll Modern natural rustic grey/red Brick stone wall wallpaper hotel background wall decor pvc wallpaper",
                "minOrder": 7,
                "lots": "7Piece/Lot",
                "measure": "Piece"
            },
            {
                "discountPrice": "2.64",
                "discountRate": 5,
                "imgUrl": "http://www.dhresource.com/albu_888521956_00/1.0x0.jpg",
                "itemCode": "206996950",
                "maxPrice": 2.78,
                "minPrice": 2.57,
                "originalPrice": 2.64,
                "promoType": "40",
                "seoName": "fine-decor-wallpaper-roll-modern-natural",
                "supplierId": "ff80808131adf1ce0131bdedbf443213",
                "title": "Wholesale - Fine decor wallpaper roll Modern natural rustic grey/red Brick stone wall wallpaper hotel background wall decor pvc wallpaper",
                "minOrder": 7,
                "lots": "7Piece/Lot",
                "measure": "Piece"
            }
        ]
    },
    "message":"Success",
    "serverTime":1444460214692,
    "state":"0x0000"
}