/**
 * module src: placeOrder/tpl/placeOrderTpl.js
 * placeOrder初始化模板
**/
define('appTpl/placeOrderTpl', [], function(){
    return {
        //外层包裹容器
        header: [
            '<div class="header-back clearfix">',
                '<a class="det-back" href="javascript:window.location = document.referrer;"><span>Back</span></a>',
                '<span class="det-hdtitle">Order Review</span>',
            '</div>'
        ],
        //支付流程页面进度提示
         payProcess: [
            '<div class="process-bar process-paySucc">',
                '<span>PLACE ORDER</span>',
                '<span>PAY FOR ORDER</span>',
                '<span>SUCCESS</span>',
            '</div>'
        ],  
        //初始化金额模块
        amount:[
            '<div class="placeOd-price">',
            '<% var data = obj.orderSummary;%>',
                '<ul>',
                    '<li><span>Items Subtotal:</span><em class="j-iTotalPrice">US $<%=data.itemsSubtotal%></em></li>',
                    '<li><span>Shipping Cost:</span><em class="j-shipPrice">US $<%=data.shippingCost%></em></li>',
                    '<% if(data.couponAmount != 0){ %>',
                        '<li><span>Your Coupon:</span><em class="j-totalPrice">-US $<%=data.couponAmount%></em></li>',
                    '<% } %>',
                    '<% if(data.orderSave != 0){ %>',
                        '<li><span>(Discount:</span><div class="rt"><i class="j-totalPrice">-US $<%=data.orderSave%></i>)</div></li>',
                    '<% } %>',
                    '<% if(data.shipCostSave != 0){ %>',
                        '<li><span>(Your Save :</span><div class="rt"><i class="j-totalPrice">-US $<%=data.shipCostSave%></i>)</div></li>',
                    '<% } %>',
                    '<li class="boldStyle"><span>Grand Total:</span><em class="j-totalPrice">US $<%=data.totalPrice%></em></li>',
                '</ul>',
            '</div>'
        ],
        //初始化运输地址信息
        shippingAddress:[
                    
                    '<h3 class="plaord-tit" data-info="<%=encodeURIComponent(JSON.stringify({shippingInfo:obj.shippingInfo}))%>">Shipping Address</h3>',
                        '<% var data = obj.shippingInfo;%>',
                        '<% if (Object.keys(data) == 0) { %>',
                            '<div class="ship-addresscon j-ship-addresscon">',
                            '<a href="javascript:;"><span class="addIcon"></span>Add New Shipping Address</a>',
                        '</div>',
                        '<% } else { %>',
                            '<div class="ship-hasaddress j-ship-hasaddress">',
                                '<a href="javascript:;">',
                                    '<p><%=data.firstname %> '+'<%=data.lastname %></p>',
                                    '<p><%=data.addressline1 %>. '+'<%=data.addressline2 %></p>',
                                    '<p><%=data.city %>, '+'<%=data.state %> '+'<%=data.zipCode %></p>',
                                    '<p><%=data.countryname %></p>',
                                    '<p><%=data.tel %></p>',
                                    '<% if (data.vatnum !== "") { %>',
                                        '<p><%=data.vatnum %></p>',
                                    '<% } %>',
                               '</a>',
                            '</div>',
                        '<% } %>',
        ],
        //初始化商品信息模块
        productInfoMain:[
                '<% var dataOrders = obj.orders;%>',
                '<% var isVisitor = obj.isVisitor;%>',
                '<% for (var i = 0; i < dataOrders.length;i++){ %>',
                '<div class="j-placeOrder-main" data-info="<%=encodeURIComponent(JSON.stringify({orderId:dataOrders[i].orderId}))%>">',
                    '<div class="j-orderList pla-orderlist">',
                        '<h3 class="plaord-tit">Order<%= i+1 %>：<%=dataOrders[i].supplier.supplierName%></h3>',
                        '<% var dataOrderItemList = dataOrders[i].orderItemDTOList;%>',
                        '<% for (var j = 0; j < dataOrderItemList.length;j++){ %>',
                            '<div proid="pro3" class="j-proList pla-orderList">',
                            '<% var sellStatus = dataOrderItemList[j].cartItemDTO.sellStatus; %>', 
                            '<% var inventoryStatus = dataOrderItemList[j].cartItemDTO.inventoryStatus; %>',  
                            '<% var canDelivery = dataOrderItemList[j].cartItemDTO.canDelivery; %>',
                            '<% var cartItemId = dataOrderItemList[j].cartItemDTO.cartItemId; %>',
                                '<div class="order-details j-order-details clearfix" data-info="<%=encodeURIComponent(JSON.stringify({sellStatus:sellStatus,inventorystatus:inventoryStatus,canDelivery:canDelivery,cartItemId:cartItemId}))%>">',
                                    '<div class="od-imgcon j-od-imgcon">',
                                    '<img class="lazy" src="" data-original="<%=dataOrderItemList[j].cartItemDTO.imgURL%>" alt=""></div>',
                                    '<div class="od-con j-od-con">',
                                        '<p class="od-productit"><%=dataOrderItemList[j].cartItemDTO.prodName%></p>',
                                        '<p class="od-productAttr"><%=dataOrderItemList[j].cartItemDTO.skuInfo%></p>',
                                        '<div class="unit-price"><strong>US $<%=dataOrderItemList[j].cartItemDTO.price%></strong> / <%=dataOrderItemList[j].cartItemDTO.unit%></div>',
                                        '<div class="ui-number">',
                                            '<input class="j-numDecrease d-decrease" type="button" value="-" min="<%=dataOrderItemList[j].cartItemDTO.minQuantity%>">',
                                            '<input class="j-num d-num" type="text" max="<%=dataOrderItemList[j].cartItemDTO.maxQuantity%>" min=<%=dataOrderItemList[j].cartItemDTO.minQuantity%> value="<%=dataOrderItemList[j].cartItemDTO.quantity%>" data-value="<%=dataOrderItemList[j].cartItemDTO.quantity%>">',
                                            '<input class="j-numIncrease d-increase" type="button" value="+" max="<%=dataOrderItemList[j].cartItemDTO.maxQuantity%>">',
                                        '</div>',
                                    '</div>',
                                    '<div class="j-errorInfo error quantity-error" style="display:none;"></div>',
                                '</div>',
                                '<div class="j-shipping-cost-warp"></div>',
                                '<% if (canDelivery === true) { %>',
                                    '<div class="j-remark remark"></div>',
                                '<% } else  { %>',
                                    '<div class="j-remark remark" style="display:none;"></div>',
                                '<% } %>',
                            '</div>',
                        '<% } %>',
                    '</div>',
                    '<% if (canDelivery === true) { %>',//当是游客身份和不可运达国家时，不显示coupon信息
                        '<div class="j-coupon-warp"></div>',
                    '<% } else  { %>',
                        '<div class="j-coupon-warp" style="display:none;"></div>',
                    '<% } %>',
                '</div>',    
                '<% } %>'
        ],
        //商品信息金额、数量
        productInfoAmount:[
                '<% var dataOrders = obj.orders;%>',
                '<% for (var i = 0; i < dataOrders.length;i++){ %>',
                        '<% var dataOrderItemList = dataOrders[i].orderItemDTOList;%>',
                        '<% for (var j = 0; j < dataOrderItemList.length;j++){ %>',
                            '<p class="od-productit"><%=dataOrderItemList[j].cartItemDTO.prodName%></p>',
                            '<p class="od-productAttr"><%=dataOrderItemList[j].cartItemDTO.skuInfo%></p>',
                            '<div class="unit-price"><strong>US $<%=dataOrderItemList[j].cartItemDTO.price%></strong> / <%=dataOrderItemList[j].cartItemDTO.unit%></div>',
                            '<div class="ui-number">',
                                '<input class="j-numDecrease d-decrease" type="button" value="-" min="<%=dataOrderItemList[j].cartItemDTO.minQuantity%>">',
                                '<input class="j-num d-num" type="text" max="<%=dataOrderItemList[j].cartItemDTO.maxQuantity%>" min=<%=dataOrderItemList[j].cartItemDTO.minQuantity%> value="<%=dataOrderItemList[j].cartItemDTO.quantity%>" data-value="<%=dataOrderItemList[j].cartItemDTO.quantity%>">',
                                '<input class="j-numIncrease d-increase" type="button" value="+" max="<%=dataOrderItemList[j].cartItemDTO.maxQuantity%>">',
                            '</div>',
                            '<div class="j-errorInfo error" style="display:none;"></div>',
                        '<% if (j !== dataOrderItemList.length) { %>',
                            '@',
                        '<% } %>',
                        '<% } %>', 
                '<% } %>'
        ],
        //运输方式
        shipping :[
            '<% var dataOrders = obj.orders;%>',
            '<% for (var i = 0; i < dataOrders.length;i++){ %>',
                '<% var orderItemDTOList = obj.orders[i].orderItemDTOList; %>',
                '<% for (var j = 0; j < orderItemDTOList.length;j++){ %>',
                    '<% var leadingTime = orderItemDTOList[j].cartItemDTO.leadingTime; %>',
                    '<% var cartItemId = orderItemDTOList[j].cartItemDTO.cartItemId;%>',
                    '<% var shippingList = orderItemDTOList[j].shippingMethodList; %>',
                    '<% var canDelivery = orderItemDTOList[j].cartItemDTO.canDelivery;%>',
                    '<% var inventorystatus = orderItemDTOList[j].cartItemDTO.inventoryStatus;%>',
                    '<% var sellStatus = orderItemDTOList[j].cartItemDTO.sellStatus;%>',
                    '<% if (canDelivery === false) { %>',//是否运达国家
                        '<div class="arrowCont">',
                            '<a href="javascript:void(0);" class="select-a noSelect" data-info="<%=encodeURIComponent(JSON.stringify({orderId:dataOrders[i].orderId,cartItemId:cartItemId,canDelivery:canDelivery,inventorystatus:inventorystatus,sellStatus:sellStatus}))%>">',
                                'Shipping Cost：Undeliverable',
                            '</a>',
                        '</div>',
                        '<div class="j-errorInfo shop-cost-error">The following item(s) cannot be shipped to your country. Please provide a new address or they will automatically be removed during checkout.</div>',
                    '<% } else if(sellStatus === false) { %>',//是否可售
                        '<div class="j-errorInfo error">The following products have sold out. They will automatically be removed during checkout.</div>',
                    '<% } else  { %>',
                        '<div class="arrowCont j-shipping-cost">',
                            '<a href="javascript:void(0);" class="select-a" data-info="<%=encodeURIComponent(JSON.stringify({orderId:dataOrders[i].orderId,cartItemId:cartItemId,canDelivery:canDelivery,inventorystatus:inventorystatus,sellStatus:sellStatus}))%>">',
                                '<% if (shippingList.length > 0) { %>',
                                    '<% if (shippingList[0].freightAmountRealFinal === 0) { %>',
                                        '<p><%=shippingList[0].shippingTypeId%> <span class="freeShipping">Free Shipping</span></p>',
                                    '<% } else { %>',
                                        '<p><%=shippingList[0].shippingTypeId%>  US $<%=shippingList[0].freightAmountRealFinal%></p>',
                                    '<% } %>',
                                    '<% var day =leadingTime > 1?"days":"day" %>',
                                    '<p class="seller-ship">Seller ships within <%=leadingTime%> business <%=day%>.</p>',
                                '<% } %>',
                            '</a>',
                        '</div>',
                        '<div class="j-errorInfo shop-cost-error" style="display:none">You choosed shipping address cannot shipped to,please enter a new address.</div>',
                    '<% } %>', 
                    '<% if (j !== orderItemDTOList.length) { %>',
                        '@',
                    '<% } %>',
                '<% } %>',
            '<% } %>'       
        ],
        //运输方式信息列表
        shippingList:[
                '<div class="tit"><a href="javascript:void(0);" title="closed" class="closed j-ship-closed"></a>Shipping Cost</div>',
                '<ul class="chooseWarp j-shipList">',
                    '<% var data = obj; %>',
                    '<% for (var i = 0; i < data.length; i++){ %>',
                        '<% var orderItemDTOList = data[i].orderItemDTOList;;%>',
                        '<% for (var j = 0; j < orderItemDTOList.length; j++){ %>',
                            '<% var cartItemId = orderItemDTOList[j].cartItemDTO.cartItemId;%>',
                            '<% var shippingMethodList = orderItemDTOList[j].shippingMethodList;%>',
                            '<% for (var t = 0; t < shippingMethodList.length; t++){ %>',
                                '<% var dataSelect = shippingMethodList[t].selected;%>',
                                '<% if (dataSelect === true) { %>',
                                    '<li class="active" data-info="<%=encodeURIComponent(JSON.stringify({cartItemId:cartItemId,shippingTypeId:shippingMethodList[t].shippingTypeId}))%>">',
                                        '<% if (shippingMethodList[t].freightAmountRealFinal ===0) { %>',
                                            '<span class="rt">Free Shipping</span>',
                                        '<% } else { %>',
                                             '<span class="rt">US&nbsp;$<%=shippingMethodList[t].freightAmountRealFinal%></span>',   
                                        '<% } %>',
                                        '<strong><%=shippingMethodList[t].shippingTypeId%></strong>',
                                        '<p>delivery time: <%=shippingMethodList[t].freightCycle%> days to ship</p>',
                                    '</li>',
                                '<% } else { %>',
                                    '<li data-info="<%=encodeURIComponent(JSON.stringify({cartItemId:cartItemId,shippingTypeId:shippingMethodList[t].shippingTypeId}))%>">',
                                        '<% if (shippingMethodList[t].freightAmountRealFinal ===0) { %>',
                                            '<span class="rt">Free Shipping</span>',
                                        '<% } else { %>',
                                             '<span class="rt">US&nbsp;$<%=shippingMethodList[t].freightAmountRealFinal%></span>',   
                                        '<% } %>',
                                        '<strong><%=shippingMethodList[t].shippingTypeId%></strong>',
                                        '<p>delivery time: <%=shippingMethodList[t].freightCycle%> days to ship</span></p>',
                                    '</li>',
                                '<% } %>',
                            '<% } %>',
                        '<% } %>',
                    '<% } %>',
                '</ul>'
        ],
        //coupon
        coupon:[
                '<% var dataOrders = obj.orders; %>',
                '<% for (var i = 0; i < dataOrders.length;i++){ %>',
                    '<% var orderId = dataOrders[i].orderId; %>',
                    '<% var dataCouponDTO = dataOrders[i].couponDTO;%>',
                    '<% var campaignid = dataOrders[i].couponDTO.campaignid;%>',
                    '<div class="arrowCont j-coupon" data-info="<%=encodeURIComponent(JSON.stringify({campaignid:campaignid}))%>">',
                       '<% if(campaignid !== undefined && campaignid !=="") { %>',
                            '<a class="select-a" data-info="<%=encodeURIComponent(JSON.stringify({campaignid:campaignid,orderId:orderId}))%>"><span class="rt" style="padding-right:10px;">US $<%=dataCouponDTO.amount%></span>Select a coupon</a>',
                        '<% }else { %>',
                            '<a class="select-a" data-info="<%=encodeURIComponent(JSON.stringify({campaignid:"",orderId:orderId}))%>"><span class="rt" style="padding-right:10px;"></span>Select a coupon</a>',
                        '<% } %>',
                    '</div>',
                    '<% if (i !== dataOrders.length-1) { %>',
                        '@',
                    '<% } %>',
                '<% } %>'
        ],
        //coupon列表信息
        couponList:[
                '<div class="tit"><a href="javascript:void(0);" title="closed" class="closed j-closed j-coupon-closed"></a>Select a Coupon</div>',
                '<div class="chooseWarp">',
                    '<ul class="j-couponList">',
                        '<% var data = obj.list;%>',
                        '<% for (var i = 0; i < data.length; i++){ %>',
                            '<% var canUse = data[i].canUse;%>',
                            '<% var selected = data[i].selected;%>',
                            '<% if(selected === true) { %>',
                                '<li class="couponLi active" data-info="<%=encodeURIComponent(JSON.stringify({couponcode:data[i].couponcode,couponBuyerId:data[i].couponBuyerId,orderId:obj.orderIds,campaignid:data[i].campaignid}))%>">US $<%=data[i].amount%><%=data[i].campaignname%></li>',
                            '<% }else if(canUse === true) { %>',
                                '<li class="couponLi" data-info="<%=encodeURIComponent(JSON.stringify({couponcode:data[i].couponcode,couponBuyerId:data[i].couponBuyerId,orderId:obj.orderIds,campaignid:data[i].campaignid}))%>">US $<%=data[i].amount%><%=data[i].campaignname%></li>',
                            '<% }else{ %>',   
                                '<li class="noAvailable" data-info="<%=encodeURIComponent(JSON.stringify({couponcode:data[i].couponcode,couponBuyerId:data[i].couponBuyerId,orderId:obj.orderIds}))%>">US $<%=data[i].amount%><%=data[i].campaignname%></li>',  
                            '<% } %>',
                        '<% } %>',
                    '</ul>',
                    '<% for (var i = 0; i < data.length; i++){ %>',
                        '<% var selected = data[i].selected;%>',
                        '<% if(selected === true) { %>',
                            '<p class="j-bindCoupon bindCoupon" type="del">Don\'t use coupons.</p>',
                        '<% } %>',
                    '<% } %>',
                '</div>',
                '<div class="addCoupon clearfix">',
                    '<input type="text" value="" placeholder="Coupon Code" class="j-coupon-input"/><a href="javascript:void(0);" class="addBtn j-addBtn" type="button" data-info="<%=encodeURIComponent(JSON.stringify({orderId:obj.orderIds}))%>">Add a New Coupon</a>',
                '</div>',
                '<div class="j-errorInfo error" style="display:none;"></div>'
        ],
        //备注
        remark:[
                '<% var dataOrders = obj.orders;%>',
                '<% for (var i = 0; i < dataOrders.length;i++){ %>',
                    '<% var dataOrderItemList = dataOrders[i].orderItemDTOList;%>',
                    '<% for (var j = 0; j < dataOrderItemList.length;j++){ %>',
                            '<% var remark = dataOrderItemList[j].cartItemDTO.remark;%>',
                            '<div class="remark-textarea"><textarea maxlength="200" placeholder="Please add remark to seller here…."><%=encodeURIComponent((remark))%></textarea></div>',
                            '<div class="j-errorInfo remark-error" style="display:none;"></div>',
                        '<% if (j !== dataOrderItemList.length) { %>',
                            '@',
                        '<% } %>',
                    '<% } %>', 
                '<% } %>'
        ],
        //placeOrder按钮
        placeOrderBtn:[
                '<input type="button" class="onsubmit"  value="Place Order"/>'   
        ],

    }
});
