/**
 * module src: storeShop/tpl/storeShopTpl.js
 * 店铺基本信息模块
 **/
define('appTpl/storeShopTpl', [], function(){
    return {
        //店铺基本信息
        detailStore: [
            '<% var data = obj; %>',
                '<div class="nlsy" data-supplierid="<%=data.sellerDto.supplierid%>">',
                    '<% if(data.sellerDto.contactpersondomainname) {%>',
                         '<h1 class="store-name"><%=data.sellerDto.contactpersondomainname%></h1>',
                    '<%} else{%>',
                         '<h1 class="store-name"><%=data.sellerDto.suppliername%></h1>',
                    '<% } %>',
                    '<% if(data.sellerDto.levelId == "P") {%>',
                         '<span class="levelP"></span>',
                    '<%} else if(data.sellerDto.levelId == "T"){%>',
                          '<span class="levelT"></span>',
                    '<% } %>',
                    '<% if(data.sellerDto.sponsor == "3") {%>',//金色 钻石礼包
                         '<span class="jsponsor"></span>',
                    '<%} else if(data.sellerDto.sponsor == "2"){%>',//蓝色 白金礼包
                         '<span class="lsponsor"></span>',
                    '<%} else if(data.sellerDto.sponsor == "1"){%>',//白色 黄金礼包
                          '<span class="hsponsor"></span>',
                    '<% } %>',
                    '<% if(data.sellerDto.year == "1") {%>',
                    '<span class="year">1<sup>st</sup> Year</span>',
                    '<%} else if(data.sellerDto.year == "2"){%>',
                    '<span class="year">2<sup>nd</sup> Year</span>',
                    '<%} else if(data.sellerDto.year == "3"){%>',
                    '<span class="year">3<sup>rd</sup> Year</span>',
                    '<%} else if(data.sellerDto.year == undefined){%>',
                    '<span class="year"></span>',
                    '<%} else {%>',
                    '<span class="year"><%=data.sellerDto.year%><sup>th</sup> Year</span>',
                    '<% } %>',
                '</div>',
                '<div class="ft">',
                    '<b><%=data.sellerDto.cofirmorderAccumulated%></b> Transactions,&nbsp;<b><%=data.sellerDto.showpercentum%>%</b> Positive Feedback',
                '</div>',
        ],
     messageEntrance:[
         '<% var data = obj; %>',
         '<% if(data.ntalkerDto.isonLine === true) {%>',
              '<a onClick="javascript:ga(\'send\',\'event\',\'Store\',\'chat\')" href="javascript:;" id="J_dhChat" ntalker_buyerid="<%=data.ntalkerDto.ntalkerBuyerid%>" class="detail-a detail-arrow-right"><b class="chat-icon"></b>Contact Seller</a>',
         '<%} else{%>',
             '<a onClick="javascript:ga(\'send\',\'event\',\'Store\',\'message\')" id="J_dhMsg" class="detail-a detail-arrow-right" href="/sendmsg.do?mty=13&spid=<%=data.sellerDto.systemuserid%>"><b class="chat-icon"></b>Contact Seller</a>',
         '<% } %>',
        ],
    promotionBanner:[
        '<% var data = obj.sellerDto; %>',
        '<% if(data.activityType !== "" && data.activityType !== undefined) {%>',
            '<div class="store-promotion">',
                '<% if(data.activityType == "1") {%>',
                    '<a class="limits" href="javascript:;">',
                        '<span class="storeEnlf"></span>',
                        '<span class="midTxt">',
                            '<var>App-Exclusive Price Time Limited & Quantity Sale</var>',
                        '<span class="storeEnRi"></span>',
                    '</a>',
                '<%} else if(data.activityType == "2"){%>',
                    '<a class="allStore" href="javascript:;">',
                        '<span class="storeEnlf"></span>',
                        '<span class="midTxt">',
                            '<var>Store-Wide Sale</var>',
                        '<span class="storeEnRi"></span>',
                    '</a>',
                '<%} else if(data.activityType == "3"){%>',
                    '<a class="allStore" href="javascript:;">',
                        '<span class="storeEnlf"></span>',
                        '<span class="midTxt">',
                            '<var>App-Exclusive Store-Wide Sale</var>',
                        '<span class="storeEnRi"></span>',
                    '</a>',
                '<%} else if(data.activityType == "4"){%>',
                    '<a class="allStore" href="javascript:;">',
                        '<span class="storeEnlf"></span>',
                        '<span class="midTxt">',
                            '<var>App-Exclusive Store-Wide Sale</var>',
                        '<span class="storeEnRi"></span>',
                    '</a>',
                    '<a class="limits" href="javascript:;">',
                        '<span class="storeEnlf"></span>',
                        '<span class="midTxt">',
                            '<var>App-Exclusive Price Time Limited & Quantity Sale</var>',
                        '<span class="storeEnRi"></span>',
                    '</a>',
                '<%} else if(data.activityType == "5"){%>',
                    '<a class="allStore" href="javascript:;">',
                        '<span class="storeEnlf"></span>',
                        '<span class="midTxt">',
                            '<var>Store-Wide Sale</var>',
                        '<span class="storeEnRi"></span>',
                    '</a>',
                    '<a class="limits" href="javascript:;">',
                        '<span class="storeEnlf"></span>',
                        '<span class="midTxt">',
                            '<var>App-Exclusive Price Time Limited & Quantity Sale</var>',
                        '<span class="storeEnRi"></span>',
                    '</a>',
                '<% } %>',
            '</div>',
        '<% } %>'
        ]
    };
});

