//公用头尾依赖的公用tools
$IMPORT('src/common/tools/fastclick.js');
$IMPORT('src/common/tools/jquery.cookie.js');
$IMPORT('src/common/tools/deeplink.js');
//公用头尾依赖的公用业务功能模板
$IMPORT('src/common/tpl/appSpreadTpl.js');
$IMPORT('src/common/tpl/header/hotKeyWordTpl.js');
$IMPORT('src/common/tpl/header/recentKeyWordTpl.js');
$IMPORT('src/common/tpl/header/suggestTpl.js');
$IMPORT('src/common/tpl/header/topMenuInitTpl.js');
$IMPORT('src/common/tpl/header/topMenuOneCategoriesTpl.js');
$IMPORT('src/common/tpl/header/turnToLanguagesWebsiteTpl.js');
//公用头尾依赖的公用业务功能模块
$IMPORT('src/common/config.js');
$IMPORT('src/common/langLoader.js');
$IMPORT('src/common/serverTime.js');
$IMPORT('src/common/appopen.js');
$IMPORT('src/common/appSpread.js');
$IMPORT('src/common/header/buyerUserInfo.js');
$IMPORT('src/common/header/hotKeyWord.js');
$IMPORT('src/common/header/recentKeyWord.js');
$IMPORT('src/common/header/suggest.js');
$IMPORT('src/common/header/topSearch.js');
$IMPORT('src/common/header/topMenuInit.js');
$IMPORT('src/common/header/topMenuOneCategories.js');
$IMPORT('src/common/header/turnToLanguagesWebsite.js');
$IMPORT('src/common/sharesns.js');
$IMPORT('src/common/checkoutflow/dataErrorLog.js');
$IMPORT('src/common/header/index.js');
$IMPORT('src/common/header/main.js');


