$axure.loadCurrentPage({
  "url":"wap-__-_______-new_home.html",
  "generationDate":new Date(1451376400255.58),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"a27e7901bb164baa8c1c45467f1f40f3",
    "type":"Axure:Page",
    "name":"wap-菜单-增加专属价入口-new home",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"f242fc4aaa4847f2a76dbe5ff297e1df",
          "label":"主menu",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"335680c9431949e1ac3c1a79aff032c5",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"39ca14d873194082ab649c2b640a2543",
                  "label":"",
                  "parentDynamicPanel":"f242fc4aaa4847f2a76dbe5ff297e1df",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "location":{
                      "x":38,
                      "y":152},
                    "size":{
                      "width":162,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a7e282cb13d04e6888e497764c5bc2e0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f242fc4aaa4847f2a76dbe5ff297e1df",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "location":{
                          "x":38,
                          "y":152},
                        "size":{
                          "width":162,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"03d06e5f41924057ade719db89a02c73",
                  "label":"",
                  "parentDynamicPanel":"f242fc4aaa4847f2a76dbe5ff297e1df",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":14,
                      "y":151},
                    "size":{
                      "width":12,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7a1d2dedbf1a47c688dc7e460e4b5cd2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f242fc4aaa4847f2a76dbe5ff297e1df",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":14,
                          "y":151},
                        "size":{
                          "width":12,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/wap-__-_______-new_home/u3.png"}},
{
                  "id":"61407f867be7458292de5213962e2310",
                  "label":"",
                  "parentDynamicPanel":"f242fc4aaa4847f2a76dbe5ff297e1df",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":413,
                      "height":140},
                    "rotation":"0",
                    "textRotation":"0",
                    "borderWidth":"0",
                    "cornerRadiusTopLeft":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d191ff63375d4865811d3f19a1b2c66b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f242fc4aaa4847f2a76dbe5ff297e1df",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":413,
                          "height":140},
                        "rotation":"0",
                        "textRotation":"0",
                        "borderWidth":"0",
                        "cornerRadiusTopLeft":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/wap-__-_______-new_home/u5.png"}},
{
                  "id":"233ecb2fd5514dac859c8b119fed3ec4",
                  "label":"",
                  "parentDynamicPanel":"f242fc4aaa4847f2a76dbe5ff297e1df",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":195},
                    "size":{
                      "width":413,
                      "height":225},
                    "rotation":"0",
                    "textRotation":"0",
                    "borderWidth":"0",
                    "cornerRadiusTopLeft":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1eecf38107d04344adf2dd9c8a6b15ea",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f242fc4aaa4847f2a76dbe5ff297e1df",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":195},
                        "size":{
                          "width":413,
                          "height":225},
                        "rotation":"0",
                        "textRotation":"0",
                        "borderWidth":"0",
                        "cornerRadiusTopLeft":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/wap-__-_______-new_home/u7.png"}},
{
                  "id":"660841edb65340d599d842166d45d3e0",
                  "label":"",
                  "parentDynamicPanel":"f242fc4aaa4847f2a76dbe5ff297e1df",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":0,
                      "y":185},
                    "size":{
                      "width":413,
                      "height":9},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"bfb68f4199914252b6812bc767293f93",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f242fc4aaa4847f2a76dbe5ff297e1df",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "location":{
                          "x":0,
                          "y":185},
                        "size":{
                          "width":413,
                          "height":9},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/wap-__-_______-new_home/u9.png"}},
{
                  "id":"4ab6359631e94b67a04b366bf1066baa",
                  "label":"",
                  "parentDynamicPanel":"f242fc4aaa4847f2a76dbe5ff297e1df",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":0,
                      "y":418},
                    "size":{
                      "width":413,
                      "height":9},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"68f29d85c8114e7ebf31953ac335791b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f242fc4aaa4847f2a76dbe5ff297e1df",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "location":{
                          "x":0,
                          "y":418},
                        "size":{
                          "width":413,
                          "height":9},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/wap-__-_______-new_home/u9.png"}},
{
                  "id":"1a54323adf9a445cabab334915c0f61d",
                  "label":"",
                  "parentDynamicPanel":"f242fc4aaa4847f2a76dbe5ff297e1df",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":370,
                      "y":50},
                    "size":{
                      "width":30,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"cf1ccf97341e4454aca48be15850ce02",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f242fc4aaa4847f2a76dbe5ff297e1df",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":370,
                          "y":50},
                        "size":{
                          "width":30,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/wap-__-_______-new_home/u13.png"}},
{
                  "id":"cd336060623f4fe3966074f78e158673",
                  "label":"",
                  "parentDynamicPanel":"f242fc4aaa4847f2a76dbe5ff297e1df",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":370,
                      "y":200},
                    "size":{
                      "width":30,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"01c6c33dba5d41dd8a94335a6d4ee3af",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f242fc4aaa4847f2a76dbe5ff297e1df",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":370,
                          "y":200},
                        "size":{
                          "width":30,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/wap-__-_______-new_home/u13.png"}},
{
                  "id":"b9eb555c673c4752a933ecd0b596c017",
                  "label":"",
                  "parentDynamicPanel":"f242fc4aaa4847f2a76dbe5ff297e1df",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":370,
                      "y":243},
                    "size":{
                      "width":30,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"21bd6a4d960d4f36b38dfb4f796e106d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f242fc4aaa4847f2a76dbe5ff297e1df",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":370,
                          "y":243},
                        "size":{
                          "width":30,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/wap-__-_______-new_home/u13.png"}},
{
                  "id":"3601256583a6400887a67fcaa670fe9c",
                  "label":"",
                  "parentDynamicPanel":"f242fc4aaa4847f2a76dbe5ff297e1df",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":370,
                      "y":293},
                    "size":{
                      "width":30,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"896dcb19e6c141c29b6c9b34db5bb462",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f242fc4aaa4847f2a76dbe5ff297e1df",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":370,
                          "y":293},
                        "size":{
                          "width":30,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/wap-__-_______-new_home/u13.png"}},
{
                  "id":"fcdc03a4745f4d86909a7cf7f562717d",
                  "label":"",
                  "parentDynamicPanel":"f242fc4aaa4847f2a76dbe5ff297e1df",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":370,
                      "y":333},
                    "size":{
                      "width":30,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b5fdca81ed124e3385864b3ba343c1f3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f242fc4aaa4847f2a76dbe5ff297e1df",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":370,
                          "y":333},
                        "size":{
                          "width":30,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/wap-__-_______-new_home/u13.png"}},
{
                  "id":"3eb0219b4b914d73bb0265005194c327",
                  "label":"",
                  "parentDynamicPanel":"f242fc4aaa4847f2a76dbe5ff297e1df",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":370,
                      "y":378},
                    "size":{
                      "width":30,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"19fe90fe91b4486e8449ea26a53b365e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f242fc4aaa4847f2a76dbe5ff297e1df",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":370,
                          "y":378},
                        "size":{
                          "width":30,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/wap-__-_______-new_home/u13.png"}},
{
                  "id":"4f09302c6f504de58a7d7c3e17cda0ee",
                  "label":"",
                  "parentDynamicPanel":"f242fc4aaa4847f2a76dbe5ff297e1df",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":340,
                      "y":200},
                    "size":{
                      "width":60,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b6c6e65ab91f466e979b74f9f764304d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f242fc4aaa4847f2a76dbe5ff297e1df",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":340,
                          "y":200},
                        "size":{
                          "width":60,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/wap-__-_______-new_home/u25.png"}},
{
                  "id":"3116ab256f5c4ac0815a6ed9a461bff5",
                  "label":"",
                  "parentDynamicPanel":"f242fc4aaa4847f2a76dbe5ff297e1df",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"18px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "location":{
                      "x":150,
                      "y":204},
                    "size":{
                      "width":23,
                      "height":22}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e6006356dda9400eab6d109c438b37af",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f242fc4aaa4847f2a76dbe5ff297e1df",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"18px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1},
                        "location":{
                          "x":150,
                          "y":204},
                        "size":{
                          "width":23,
                          "height":22}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"ad3b816126e4498584a6e6eebd7bbd85",
                  "label":"",
                  "parentDynamicPanel":"f242fc4aaa4847f2a76dbe5ff297e1df",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":300,
                      "y":430},
                    "size":{
                      "width":70,
                      "height":33},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"db50f104b26041419c4ebfdf4f87f549",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f242fc4aaa4847f2a76dbe5ff297e1df",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":300,
                          "y":430},
                        "size":{
                          "width":70,
                          "height":33},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/wap-__-_______-new_home/u29.png"}},
{
                  "id":"504e6ed40e0d4eef9d00a30547813980",
                  "label":"",
                  "parentDynamicPanel":"f242fc4aaa4847f2a76dbe5ff297e1df",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"18px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "location":{
                      "x":309,
                      "y":437},
                    "size":{
                      "width":60,
                      "height":22}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4b1ff6419292487eaba6c6c94416c1a4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f242fc4aaa4847f2a76dbe5ff297e1df",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"18px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1},
                        "location":{
                          "x":309,
                          "y":437},
                        "size":{
                          "width":60,
                          "height":22}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"043452036b554c1aad0647cf428c5641",
                  "label":"",
                  "parentDynamicPanel":"f242fc4aaa4847f2a76dbe5ff297e1df",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":93},
                    "size":{
                      "width":413,
                      "height":47}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"Show categories slide left 300 ms,<br>Hide 主menu slide left 300 ms",
                              "objectsToFades":[{
                                  "objectPath":["3851d86d1cc9444f84d8c628f3609989"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "easing":"slideLeft",
                                      "duration":300,
                                      "showType":"none"}}},
{
                                  "objectPath":["f242fc4aaa4847f2a76dbe5ff297e1df"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "easing":"slideLeft",
                                      "duration":300,
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true},
{
                  "id":"9b0f60308da843a1930be25d0b7a2857",
                  "label":"",
                  "parentDynamicPanel":"f242fc4aaa4847f2a76dbe5ff297e1df",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":360,
                      "y":0},
                    "size":{
                      "width":50,
                      "height":50}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"Hide 主menu slide left 300 ms",
                              "objectsToFades":[{
                                  "objectPath":["f242fc4aaa4847f2a76dbe5ff297e1df"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "easing":"slideLeft",
                                      "duration":300,
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true},
{
                  "id":"50e35def42b44b4db87b166459261fa6",
                  "label":"",
                  "parentDynamicPanel":"f242fc4aaa4847f2a76dbe5ff297e1df",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":2,
                      "y":431},
                    "size":{
                      "width":173,
                      "height":74}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fdcab174ba7744189dabdafe80190851",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f242fc4aaa4847f2a76dbe5ff297e1df",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":2,
                          "y":431},
                        "size":{
                          "width":173,
                          "height":74}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/wap-__-_______-new_home/u35.png"}},
{
                  "id":"6044f97d8bbc40b299c85c36cfb4cd95",
                  "label":"",
                  "parentDynamicPanel":"f242fc4aaa4847f2a76dbe5ff297e1df",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":0,
                      "y":515},
                    "size":{
                      "width":413,
                      "height":9},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"df85dadfb757439d9e309f8bea372692",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f242fc4aaa4847f2a76dbe5ff297e1df",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "location":{
                          "x":0,
                          "y":515},
                        "size":{
                          "width":413,
                          "height":9},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/wap-__-_______-new_home/u9.png"}},
{
                  "id":"4716cceb83a44356b8953a3460352249",
                  "label":"",
                  "parentDynamicPanel":"f242fc4aaa4847f2a76dbe5ff297e1df",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":36,
                      "y":534},
                    "size":{
                      "width":85,
                      "height":29}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"cc54c36796404629bde724540897a12e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f242fc4aaa4847f2a76dbe5ff297e1df",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":36,
                          "y":534},
                        "size":{
                          "width":85,
                          "height":29}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/wap-__-_______-new_home/u39.png"}},
{
                  "id":"0f838417916248618782ff3f10cc43ba",
                  "label":"",
                  "parentDynamicPanel":"f242fc4aaa4847f2a76dbe5ff297e1df",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":427},
                    "size":{
                      "width":413,
                      "height":47}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"Show language slide left 300 ms,<br>Hide 主menu slide left 300 ms",
                              "objectsToFades":[{
                                  "objectPath":["f242fc4aaa4847f2a76dbe5ff297e1df"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "easing":"slideLeft",
                                      "duration":300,
                                      "showType":"none"}}},
{
                                  "objectPath":["8a01f61009884185b45e3a8b220ab9de"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "easing":"slideLeft",
                                      "duration":300,
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true}]}]},
{
          "id":"ed1512e1fa3f45a7b0139689deeee30d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":423,
              "y":30},
            "size":{
              "width":183,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f7d773260ff841b59d8daa3a1560c092",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":423,
                  "y":30},
                "size":{
                  "width":183,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b436feb426024fedae5226f38dc519f7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":423,
              "y":61},
            "size":{
              "width":361,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4f9b74d65f024b938a88b684af23fb5a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":423,
                  "y":61},
                "size":{
                  "width":361,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3851d86d1cc9444f84d8c628f3609989",
          "label":"categories",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "size":{
              "width":10,
              "height":10},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"d5cb178749bb4d3f85d445e456b41e6d",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"f6d01d85ac3446cc95faef3c158f0f96",
                  "label":"",
                  "parentDynamicPanel":"3851d86d1cc9444f84d8c628f3609989",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":415,
                      "height":737}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b23fd9e203da4aa180b1fd9a75bb58a3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3851d86d1cc9444f84d8c628f3609989",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":415,
                          "height":737}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/wap-__-_______-new_home/u47.png"}},
{
                  "id":"d06ef8c760d54e578380d96efe44ed9b",
                  "label":"",
                  "parentDynamicPanel":"3851d86d1cc9444f84d8c628f3609989",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":370,
                      "y":10},
                    "size":{
                      "width":30,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"Hide categories slide left 300 ms",
                              "objectsToFades":[{
                                  "objectPath":["3851d86d1cc9444f84d8c628f3609989"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "easing":"slideLeft",
                                      "duration":300,
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true},
{
                  "id":"a1db33f3e01241d5abbff40a8fb48ca8",
                  "label":"",
                  "parentDynamicPanel":"3851d86d1cc9444f84d8c628f3609989",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":3},
                    "size":{
                      "width":130,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"Hide categories slide right 300 ms",
                              "objectsToFades":[{
                                  "objectPath":["3851d86d1cc9444f84d8c628f3609989"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "easing":"slideRight",
                                      "duration":300,
                                      "showType":"none"}}}]},
{
                              "action":"fadeWidget",
                              "description":"Show 主menu slide right 300 ms",
                              "objectsToFades":[{
                                  "objectPath":["f242fc4aaa4847f2a76dbe5ff297e1df"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "easing":"slideRight",
                                      "duration":300,
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true}]}]},
{
          "id":"887f7928a65542b9946ee3c0e2cbafec",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":440,
              "y":100},
            "size":{
              "width":359,
              "height":112}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7dd22629a63645b8bf7de449a30058bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":440,
                  "y":100},
                "size":{
                  "width":359,
                  "height":112}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8a01f61009884185b45e3a8b220ab9de",
          "label":"language",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":-10,
              "y":0},
            "size":{
              "width":10,
              "height":10},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"38af34f9d1a2412f81c09c96bb6edfb6",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"6a518d7485e04bfba0251d72a9b38e25",
                  "label":"",
                  "parentDynamicPanel":"8a01f61009884185b45e3a8b220ab9de",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":415,
                      "height":737}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2c7354f895f0406db273230219312a46",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"8a01f61009884185b45e3a8b220ab9de",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":415,
                          "height":737}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/wap-__-_______-new_home/u47.png"}},
{
                  "id":"b7e10c90344847609305271970f034db",
                  "label":"",
                  "parentDynamicPanel":"8a01f61009884185b45e3a8b220ab9de",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":53},
                    "size":{
                      "width":415,
                      "height":657},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"24311a9841e94677a3053c80236b265c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"8a01f61009884185b45e3a8b220ab9de",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":53},
                        "size":{
                          "width":415,
                          "height":657},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/wap-__-_______-new_home/u56.png"}},
{
                  "id":"72ec0216f9f14382a64585cd15006223",
                  "label":"",
                  "parentDynamicPanel":"8a01f61009884185b45e3a8b220ab9de",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":370,
                      "y":10},
                    "size":{
                      "width":30,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"Hide language slide left 300 ms",
                              "objectsToFades":[{
                                  "objectPath":["8a01f61009884185b45e3a8b220ab9de"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "easing":"slideLeft",
                                      "duration":300,
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true},
{
                  "id":"246cd0030f3f4425bbfb418b63c99d34",
                  "label":"",
                  "parentDynamicPanel":"8a01f61009884185b45e3a8b220ab9de",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":3},
                    "size":{
                      "width":130,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"Hide language slide right 300 ms",
                              "objectsToFades":[{
                                  "objectPath":["8a01f61009884185b45e3a8b220ab9de"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "easing":"slideRight",
                                      "duration":300,
                                      "showType":"none"}}}]},
{
                              "action":"fadeWidget",
                              "description":"Show 主menu slide right 300 ms",
                              "objectsToFades":[{
                                  "objectPath":["f242fc4aaa4847f2a76dbe5ff297e1df"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "easing":"slideRight",
                                      "duration":300,
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true},
{
                  "id":"c6bb2577c040468083f6d2cb381e76fd",
                  "label":"",
                  "parentDynamicPanel":"8a01f61009884185b45e3a8b220ab9de",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":2,
                      "y":44},
                    "size":{
                      "width":409,
                      "height":315},
                    "rotation":"0",
                    "textRotation":"0",
                    "borderWidth":"0",
                    "cornerRadiusTopLeft":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c036b4d60f7e4e3898372b327566962b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"8a01f61009884185b45e3a8b220ab9de",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":2,
                          "y":44},
                        "size":{
                          "width":409,
                          "height":315},
                        "rotation":"0",
                        "textRotation":"0",
                        "borderWidth":"0",
                        "cornerRadiusTopLeft":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/wap-__-_______-new_home/u60.png"}},
{
                  "id":"d5cedcf473d54517aca2be47e548715d",
                  "label":"",
                  "parentDynamicPanel":"8a01f61009884185b45e3a8b220ab9de",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":4,
                      "y":53},
                    "size":{
                      "width":118,
                      "height":34}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b82f00f6989b4f8fac6ae2c3b3e20d1c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"8a01f61009884185b45e3a8b220ab9de",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":4,
                          "y":53},
                        "size":{
                          "width":118,
                          "height":34}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/wap-__-_______-new_home/u62.png"}},
{
                  "id":"fc86c4793db04ae3879f7666eb1834bb",
                  "label":"",
                  "parentDynamicPanel":"8a01f61009884185b45e3a8b220ab9de",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":99},
                    "size":{
                      "width":121,
                      "height":31}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7b89d6cdd44847e48114b4b5ec1d44d9",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"8a01f61009884185b45e3a8b220ab9de",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":99},
                        "size":{
                          "width":121,
                          "height":31}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/wap-__-_______-new_home/u64.png"}},
{
                  "id":"3c20b760d90848dfa4c07ed35f667202",
                  "label":"",
                  "parentDynamicPanel":"8a01f61009884185b45e3a8b220ab9de",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":4,
                      "y":145},
                    "size":{
                      "width":134,
                      "height":32}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2f3026e5f2d7499f8b5fbec0ca5ac6a2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"8a01f61009884185b45e3a8b220ab9de",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":4,
                          "y":145},
                        "size":{
                          "width":134,
                          "height":32}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/wap-__-_______-new_home/u66.png"}},
{
                  "id":"1d81c1c40dc84c95b7e41a1eaaaa9181",
                  "label":"",
                  "parentDynamicPanel":"8a01f61009884185b45e3a8b220ab9de",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":5,
                      "y":187},
                    "size":{
                      "width":122,
                      "height":31}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8958e5dd28174f38b769d0c52342d568",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"8a01f61009884185b45e3a8b220ab9de",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":5,
                          "y":187},
                        "size":{
                          "width":122,
                          "height":31}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/wap-__-_______-new_home/u68.png"}},
{
                  "id":"bcb76e918e3d456dbe2787f8d70c1f65",
                  "label":"",
                  "parentDynamicPanel":"8a01f61009884185b45e3a8b220ab9de",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":2,
                      "y":237},
                    "size":{
                      "width":124,
                      "height":23}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4997356bb2b24ee08395577c7fafcfed",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"8a01f61009884185b45e3a8b220ab9de",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":2,
                          "y":237},
                        "size":{
                          "width":124,
                          "height":23}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/wap-__-_______-new_home/u70.png"}},
{
                  "id":"dd21304a50294fa8b7084c8eb402c812",
                  "label":"",
                  "parentDynamicPanel":"8a01f61009884185b45e3a8b220ab9de",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":5,
                      "y":282},
                    "size":{
                      "width":113,
                      "height":26}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0cf7555138df48b8b3a6a7a7a8aa43ce",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"8a01f61009884185b45e3a8b220ab9de",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":5,
                          "y":282},
                        "size":{
                          "width":113,
                          "height":26}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/wap-__-_______-new_home/u72.png"}},
{
                  "id":"bdc3972604dc486587d6b45c981dd2cb",
                  "label":"",
                  "parentDynamicPanel":"8a01f61009884185b45e3a8b220ab9de",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":3,
                      "y":324},
                    "size":{
                      "width":107,
                      "height":29}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4bd3e7f282d24dafba0298da08efdb44",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"8a01f61009884185b45e3a8b220ab9de",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":3,
                          "y":324},
                        "size":{
                          "width":107,
                          "height":29}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/wap-__-_______-new_home/u74.png"}},
{
                  "id":"f267713b8b484ab5b1b0febc793c0891",
                  "label":"",
                  "parentDynamicPanel":"8a01f61009884185b45e3a8b220ab9de",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":363},
                    "size":{
                      "width":415,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/wap-__-_______-new_home/u76_line.png"}}]}]},
{
          "id":"18a250a54bfb4115a968728c27959dc0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":440,
              "y":240},
            "size":{
              "width":182,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"875b8e9e225e447ab0cd221693867c1c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":440,
                  "y":240},
                "size":{
                  "width":182,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "f242fc4aaa4847f2a76dbe5ff297e1df":{
      "scriptId":"u0"},
    "39ca14d873194082ab649c2b640a2543":{
      "scriptId":"u1"},
    "a7e282cb13d04e6888e497764c5bc2e0":{
      "scriptId":"u2"},
    "03d06e5f41924057ade719db89a02c73":{
      "scriptId":"u3"},
    "7a1d2dedbf1a47c688dc7e460e4b5cd2":{
      "scriptId":"u4"},
    "61407f867be7458292de5213962e2310":{
      "scriptId":"u5"},
    "d191ff63375d4865811d3f19a1b2c66b":{
      "scriptId":"u6"},
    "233ecb2fd5514dac859c8b119fed3ec4":{
      "scriptId":"u7"},
    "1eecf38107d04344adf2dd9c8a6b15ea":{
      "scriptId":"u8"},
    "660841edb65340d599d842166d45d3e0":{
      "scriptId":"u9"},
    "bfb68f4199914252b6812bc767293f93":{
      "scriptId":"u10"},
    "4ab6359631e94b67a04b366bf1066baa":{
      "scriptId":"u11"},
    "68f29d85c8114e7ebf31953ac335791b":{
      "scriptId":"u12"},
    "1a54323adf9a445cabab334915c0f61d":{
      "scriptId":"u13"},
    "cf1ccf97341e4454aca48be15850ce02":{
      "scriptId":"u14"},
    "cd336060623f4fe3966074f78e158673":{
      "scriptId":"u15"},
    "01c6c33dba5d41dd8a94335a6d4ee3af":{
      "scriptId":"u16"},
    "b9eb555c673c4752a933ecd0b596c017":{
      "scriptId":"u17"},
    "21bd6a4d960d4f36b38dfb4f796e106d":{
      "scriptId":"u18"},
    "3601256583a6400887a67fcaa670fe9c":{
      "scriptId":"u19"},
    "896dcb19e6c141c29b6c9b34db5bb462":{
      "scriptId":"u20"},
    "fcdc03a4745f4d86909a7cf7f562717d":{
      "scriptId":"u21"},
    "b5fdca81ed124e3385864b3ba343c1f3":{
      "scriptId":"u22"},
    "3eb0219b4b914d73bb0265005194c327":{
      "scriptId":"u23"},
    "19fe90fe91b4486e8449ea26a53b365e":{
      "scriptId":"u24"},
    "4f09302c6f504de58a7d7c3e17cda0ee":{
      "scriptId":"u25"},
    "b6c6e65ab91f466e979b74f9f764304d":{
      "scriptId":"u26"},
    "3116ab256f5c4ac0815a6ed9a461bff5":{
      "scriptId":"u27"},
    "e6006356dda9400eab6d109c438b37af":{
      "scriptId":"u28"},
    "ad3b816126e4498584a6e6eebd7bbd85":{
      "scriptId":"u29"},
    "db50f104b26041419c4ebfdf4f87f549":{
      "scriptId":"u30"},
    "504e6ed40e0d4eef9d00a30547813980":{
      "scriptId":"u31"},
    "4b1ff6419292487eaba6c6c94416c1a4":{
      "scriptId":"u32"},
    "043452036b554c1aad0647cf428c5641":{
      "scriptId":"u33"},
    "9b0f60308da843a1930be25d0b7a2857":{
      "scriptId":"u34"},
    "50e35def42b44b4db87b166459261fa6":{
      "scriptId":"u35"},
    "fdcab174ba7744189dabdafe80190851":{
      "scriptId":"u36"},
    "6044f97d8bbc40b299c85c36cfb4cd95":{
      "scriptId":"u37"},
    "df85dadfb757439d9e309f8bea372692":{
      "scriptId":"u38"},
    "4716cceb83a44356b8953a3460352249":{
      "scriptId":"u39"},
    "cc54c36796404629bde724540897a12e":{
      "scriptId":"u40"},
    "0f838417916248618782ff3f10cc43ba":{
      "scriptId":"u41"},
    "ed1512e1fa3f45a7b0139689deeee30d":{
      "scriptId":"u42"},
    "f7d773260ff841b59d8daa3a1560c092":{
      "scriptId":"u43"},
    "b436feb426024fedae5226f38dc519f7":{
      "scriptId":"u44"},
    "4f9b74d65f024b938a88b684af23fb5a":{
      "scriptId":"u45"},
    "3851d86d1cc9444f84d8c628f3609989":{
      "scriptId":"u46"},
    "f6d01d85ac3446cc95faef3c158f0f96":{
      "scriptId":"u47"},
    "b23fd9e203da4aa180b1fd9a75bb58a3":{
      "scriptId":"u48"},
    "d06ef8c760d54e578380d96efe44ed9b":{
      "scriptId":"u49"},
    "a1db33f3e01241d5abbff40a8fb48ca8":{
      "scriptId":"u50"},
    "887f7928a65542b9946ee3c0e2cbafec":{
      "scriptId":"u51"},
    "7dd22629a63645b8bf7de449a30058bd":{
      "scriptId":"u52"},
    "8a01f61009884185b45e3a8b220ab9de":{
      "scriptId":"u53"},
    "6a518d7485e04bfba0251d72a9b38e25":{
      "scriptId":"u54"},
    "2c7354f895f0406db273230219312a46":{
      "scriptId":"u55"},
    "b7e10c90344847609305271970f034db":{
      "scriptId":"u56"},
    "24311a9841e94677a3053c80236b265c":{
      "scriptId":"u57"},
    "72ec0216f9f14382a64585cd15006223":{
      "scriptId":"u58"},
    "246cd0030f3f4425bbfb418b63c99d34":{
      "scriptId":"u59"},
    "c6bb2577c040468083f6d2cb381e76fd":{
      "scriptId":"u60"},
    "c036b4d60f7e4e3898372b327566962b":{
      "scriptId":"u61"},
    "d5cedcf473d54517aca2be47e548715d":{
      "scriptId":"u62"},
    "b82f00f6989b4f8fac6ae2c3b3e20d1c":{
      "scriptId":"u63"},
    "fc86c4793db04ae3879f7666eb1834bb":{
      "scriptId":"u64"},
    "7b89d6cdd44847e48114b4b5ec1d44d9":{
      "scriptId":"u65"},
    "3c20b760d90848dfa4c07ed35f667202":{
      "scriptId":"u66"},
    "2f3026e5f2d7499f8b5fbec0ca5ac6a2":{
      "scriptId":"u67"},
    "1d81c1c40dc84c95b7e41a1eaaaa9181":{
      "scriptId":"u68"},
    "8958e5dd28174f38b769d0c52342d568":{
      "scriptId":"u69"},
    "bcb76e918e3d456dbe2787f8d70c1f65":{
      "scriptId":"u70"},
    "4997356bb2b24ee08395577c7fafcfed":{
      "scriptId":"u71"},
    "dd21304a50294fa8b7084c8eb402c812":{
      "scriptId":"u72"},
    "0cf7555138df48b8b3a6a7a7a8aa43ce":{
      "scriptId":"u73"},
    "bdc3972604dc486587d6b45c981dd2cb":{
      "scriptId":"u74"},
    "4bd3e7f282d24dafba0298da08efdb44":{
      "scriptId":"u75"},
    "f267713b8b484ab5b1b0febc793c0891":{
      "scriptId":"u76"},
    "18a250a54bfb4115a968728c27959dc0":{
      "scriptId":"u77"},
    "875b8e9e225e447ab0cd221693867c1c":{
      "scriptId":"u78"}}});