//appdeeplink页依赖的公用tools
$IMPORT('src/common/tools/jquery.cookie.js');
$IMPORT('src/common/tools/deeplink.js');
//appdeeplink页依赖公用模块
$IMPORT('src/common/config.js');
$IMPORT('src/common/langLoader.js');
//appdeeplink页功能模块
$IMPORT('src/appdeeplink/appDeeplink.js');
$IMPORT('src/appdeeplink/index.js');
$IMPORT('src/appdeeplink/main.js');