//首页依赖的公用tools
$IMPORT('src/common/tools/fastclick.js');
$IMPORT('src/common/tools/jquery.cookie.js');
$IMPORT('src/common/tools/deeplink.js');
//首页依赖的公用业务功能模板
$IMPORT('src/common/tpl/appSpreadTpl.js');
$IMPORT('src/common/tpl/header/hotKeyWordTpl.js');
$IMPORT('src/common/tpl/header/recentKeyWordTpl.js');
$IMPORT('src/common/tpl/header/suggestTpl.js');
$IMPORT('src/common/tpl/header/topMenuInitTpl.js');
$IMPORT('src/common/tpl/header/topMenuOneCategoriesTpl.js');
$IMPORT('src/common/tpl/header/turnToLanguagesWebsiteTpl.js');
//首页依赖的公用业务功能模块
$IMPORT('src/common/config.js');
$IMPORT('src/common/langLoader.js');
$IMPORT('src/common/serverTime.js');
$IMPORT('src/common/appopen.js');
$IMPORT('src/common/appSpread.js');
$IMPORT('src/common/header/buyerUserInfo.js');
$IMPORT('src/common/header/hotKeyWord.js');
$IMPORT('src/common/header/recentKeyWord.js');
$IMPORT('src/common/header/suggest.js');
$IMPORT('src/common/header/topSearch.js');
$IMPORT('src/common/header/topMenuInit.js');
$IMPORT('src/common/header/topMenuOneCategories.js');
$IMPORT('src/common/header/turnToLanguagesWebsite.js');
$IMPORT('src/common/sharesns.js');
$IMPORT('src/common/checkoutflow/dataErrorLog.js');
$IMPORT('src/common/checkoutflow/popupTip.js');
$IMPORT('src/common/tc.js');
//首页模板
$IMPORT('src/home/tpl/dailyDealsTpl.js');
$IMPORT('src/home/tpl/youMyLikeTpl.js');
$IMPORT('src/home/tpl/userAttentionTpl.js');
//首页功能模块
$IMPORT('src/home/lazyload.js');
$IMPORT('src/home/swiper.js');
$IMPORT('src/home/dailyDeals.js');
$IMPORT('src/home/userAttention.js');
$IMPORT('src/home/saveUserAttention.js');
$IMPORT('src/home/youMyLike.js');
$IMPORT('src/home/index.js');
$IMPORT('src/home/main.js');