$axure.loadCurrentPage({
  "url":"__deals____vip_club___.html",
  "generationDate":new Date(1451376400747.58),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"4ae0f50a7f0947a3883558d2b2c1fe42",
    "type":"Axure:Page",
    "name":"首页deals的位置和vip club的位置",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"d5424348a8b3461fa63f0442476d3d24",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":382,
              "height":217},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed153e1efa8449068eec021165303856",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":382,
                  "height":217},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/__deals____vip_club___/u0.png"}},
{
          "id":"a1712efbd6eb44c4af6c3efa4dccdab7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":217},
            "size":{
              "width":382,
              "height":463},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f64e581837140f0bd2764828b7e9d17",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":217},
                "size":{
                  "width":382,
                  "height":463},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/__deals____vip_club___/u2.png"}},
{
          "id":"cbbbedd5fdda42daaa2420036b2c03c6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":170,
              "y":633},
            "size":{
              "width":40,
              "height":47},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6fc08bfae29d4eb0a356f7c54c3a950b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":170,
                  "y":633},
                "size":{
                  "width":40,
                  "height":47},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/__deals____vip_club___/u4.png"}},
{
          "id":"cd1dc68f07784522900a3b61d5db3442",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":183,
              "y":635},
            "size":{
              "width":21,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c41170a9f692462da72c18e3e337bb31",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":183,
                  "y":635},
                "size":{
                  "width":21,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/__deals____vip_club___/u6.png"}},
{
          "id":"45fe4b8848f246e09135d80bad40aded",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":177,
              "y":661},
            "size":{
              "width":34,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a223e9f00896486ca46082728b83935f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":177,
                  "y":661},
                "size":{
                  "width":34,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f6ac912819694989bca911b6c5282cf0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE0E0E2},
            "location":{
              "x":239,
              "y":252},
            "size":{
              "width":100,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0e2f1635f1d0486e9c84b75d4e54a27a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE0E0E2},
                "location":{
                  "x":239,
                  "y":252},
                "size":{
                  "width":100,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/__deals____vip_club___/u10.png"}},
{
          "id":"9b3bf31760c04d44a2e1d41375c140b7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":244,
              "y":262},
            "size":{
              "width":86,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e3964fdbcaf4d0e84f7351d1b915460",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":244,
                  "y":262},
                "size":{
                  "width":86,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"50796bb6acba40e3a1774909736af50d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":402,
              "y":252},
            "size":{
              "width":248,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e56a7a1a65474754881433ae6d28acc1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":402,
                  "y":252},
                "size":{
                  "width":248,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1a4846a5671a404d9dc393324a5ae301",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":410,
              "y":648},
            "size":{
              "width":218,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ef31e64f40447f0ae1a0ef7bd814403",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":410,
                  "y":648},
                "size":{
                  "width":218,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "d5424348a8b3461fa63f0442476d3d24":{
      "scriptId":"u0"},
    "ed153e1efa8449068eec021165303856":{
      "scriptId":"u1"},
    "a1712efbd6eb44c4af6c3efa4dccdab7":{
      "scriptId":"u2"},
    "3f64e581837140f0bd2764828b7e9d17":{
      "scriptId":"u3"},
    "cbbbedd5fdda42daaa2420036b2c03c6":{
      "scriptId":"u4"},
    "6fc08bfae29d4eb0a356f7c54c3a950b":{
      "scriptId":"u5"},
    "cd1dc68f07784522900a3b61d5db3442":{
      "scriptId":"u6"},
    "c41170a9f692462da72c18e3e337bb31":{
      "scriptId":"u7"},
    "45fe4b8848f246e09135d80bad40aded":{
      "scriptId":"u8"},
    "a223e9f00896486ca46082728b83935f":{
      "scriptId":"u9"},
    "f6ac912819694989bca911b6c5282cf0":{
      "scriptId":"u10"},
    "0e2f1635f1d0486e9c84b75d4e54a27a":{
      "scriptId":"u11"},
    "9b3bf31760c04d44a2e1d41375c140b7":{
      "scriptId":"u12"},
    "1e3964fdbcaf4d0e84f7351d1b915460":{
      "scriptId":"u13"},
    "50796bb6acba40e3a1774909736af50d":{
      "scriptId":"u14"},
    "e56a7a1a65474754881433ae6d28acc1":{
      "scriptId":"u15"},
    "1a4846a5671a404d9dc393324a5ae301":{
      "scriptId":"u16"},
    "4ef31e64f40447f0ae1a0ef7bd814403":{
      "scriptId":"u17"}}});